everything2/everything2

tools/conftest.pl, vagrant/cookbooks/e2engine/recipes/default.rb
=> Removes basedir from recipes

tools/conftest.pl
=> Expands conftest to make testing items easier

vagrant/cookbooks/e2engine/recipes/default.rb
=> Removes chef recipe item for permanent nodecache

ecore/Everything/Configuration.pm
=> Adds nosearch_words to the inner configuration

vagrant/cookbooks/e2engine/recipes/default.rb
=> Removes nosearch_words from chef recipe

ecore/Everything/Configuration.pm, tools/conftest.pl
=> Adds the default for recaptcha_v3_public_key

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the recaptcha public key

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the google_ads_badnodes writing

serverless/Makefile
=> Fixes the serverless build functionality

cf/everything2-production.json, lambda/webhooks-receiver/handler.rb
=> Fixes the timeouts on lambda functions to help with larger

serverless/deplists/app.json
=> Adds the Mason plugin needed

serverless/Makefile
=> Adds libjpeg/nasm support for the perl layer

serverless/Makefile
=> Adds libpng

serverless/Makefile
=> Disables freetype and fontconfig in ImageMagick

serverless/Makefile
=> Removes webp from ImageMagick build

serverless/Makefile
=> Removes X from ImageMagick

serverless/Makefile
=> Remove pango support from ImageMagick

serverless/Makefile
=> Remove openmp from ImageMagick

cf/everything2-production.json
=> Allows lambda to connect to the e2 database

ecore/Everything/Configuration.pm
=> Check secretsmanager if secrets file does not exist

cf/everything2-production.json, lambda/everything2-library-layer-builder/handler.rb
=> Fixes lambda layer publishing and promotion

ecore/Everything/Configuration.pm
=> Adds an environment variable check for AWS_REGION for lambda

ecore/Everything/Application.pm, tools/db.pl, tools/generate_sitemap.pl
=> Fixes the sitemap for the perl version

cf/everything2-production.json
=> Fixes deletion protection for all current resources

cf/everything2-production.json, serverless/Makefile
=> Clean up old e2 perl standalone layer

ops/.gitignore, ops/deploy-opsworks-build.rb, ops/lib/e2/appstate.rb, ops/lib/e2/utils.rb
=> Get rid of secrets in deployment

serverless/bootstrap
=> Adds verbosity and more language

cf/everything2-production.json, lambda/sitemap-batch-dispatcher/handler.pl, serverless/bootstrap
=> Adds cloud error handling

ecore/Everything/Delegation/htmlcode.pm
=> Fixes a warning found with the new spiffy warnings finder

ecore/Everything/Application.pm
=> Adds more logging to the warning finder

ecore/Everything/HTML.pm
=> Swaps param for multi-param

ecore/Everything/Delegation/htmlcode.pm
=> Fixes unitialized content warning

ecore/Everything/Delegation/htmlcode.pm
=> Squash another warning

ecore/Everything/Application.pm
=> Cleans up uninitialized value

ecore/Everything/Delegation/document.pm
=> Fixes uninitialized value

ecore/Everything/Application.pm
=> Removes uninitialized value warnings

cf/everything2-production.json
=> Adds mysql parameters to fix timestamping problems

ecore/Everything/Delegation/nodelet.pm
=> Fixes uninitialized value warning in nodelet

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value in setwriteuptype

ecore/Everything/Application.pm
=> Fixed uninitialzed value

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized warning in messagebox

ecore/Everything/Application.pm
=> Fixes uninitialzed value

ecore/Everything/Delegation/document.pm
=> Fixes uninitialized warning

ecore/Everything/Application.pm, ecore/Everything/Request.pm
=> Adds new items for better warning message generation in CloudWatch

ecore/Everything/Delegation/htmlcode.pm
=> Fixes an uninialized value warning clogging up the logic

ecore/Everything/Delegation/htmlcode.pm
=> Squash that noise

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value in broken dates

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitalized value in weblogform

ecore/Everything/Delegation/htmlcode.pm
=> Fixes CGI param in list context in confirmop

ecore/Everything/HTML.pm
=> Fixes odd number of elements problem which is possibly a security hole

ecore/Everything/Application.pm
This also fixes half of the problem where you can't link to [0]
Fixes #3535
=> Uninitalized value in $nodename fixes

ecore/Everything/Delegation/htmlcode.pm
=> Fixes undefined warning (I think)

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialzed value warning

ecore/Everything/Page/sign_up.pm
=> Fixes uninitalized value in sign up

nodepack/_data/links.xml, nodepack/_data/nodegroup.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/bounty_order.xml, nodepack/setting/outlaws.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/everything's_most_wanted.xml, nodepack/superdoc/jaybonci's_sandbox.xml, nodepack/superdoc/message_outbox.xml, nodepack/user/virgil.xml, nodepack/user/webster_1913.xml
=> Fixes everything's most wanted

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninialized value warning

ecore/Everything/Delegation/htmlcode.pm
=> Uninitialized value

ecore/Everything/Delegation/htmlcode.pm
=> Fix trash warning in messagebox

ecore/Everything/Delegation/htmlcode.pm
=> Fixes a trash warning on broken dates

ops/clear-app-error-logs.rb, ops/top-app-errors.rb
=> Adds in the new helper scripts

ecore/Everything/Delegation/document.pm
=> Clean up more junk warnings

ecore/Everything/Delegation/opcode.pm
=> Fixes junk warning

ecore/Everything/Application.pm
=> Fix junk warning

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value warnings

ecore/Everything/Application.pm, ecore/Everything/Configuration.pm
=> Fixes current_region code duplication

nodepack/restricted_superdoc/ip_hunter.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/bounty_order.xml, nodepack/setting/outlaws.xml, nodepack/setting/room_topics.xml
=> Fixes warning in IP Hunter

nodepack/superdoc/node_backup.xml
=> Fixes Node Backup

ecore/Everything.pm, ecore/Everything/S3.pm, ecore/Everything/S3/BucketConfig.pm
=> Removes Net::Amazon::S3 for Paws

serverless/deplists/app.json
=> Removes Net::Amazon::S3

vagrant/cookbooks/e2engine/recipes/default.rb
=> Removes old items from the cookbooks

lambda/cicd-codebuild-perl-layer-publisher/handler.rb, lambda/cicd-zips-puller/handler.rb, lambda/everything2-library-layer-builder/handler.rb, lambda/opsworks-deregistration/handler.rb, lambda/opsworks-reaper/handler.rb, lambda/sitemap-batch-dispatcher/handler.pl, lambda/webhooks-receiver/handler.rb
=> Fixes busted lambdas

cf/everything2-production.json, lambda/sitemap-batch-dispatcher/handler.pl, lambda/sitemap-batch-processor/handler.pl
=> Fixes storage gateway

serverless/bootstrap
=> Adds debugging statement for messages to bootstrap

serverless/bootstrap
=> Captures stuff for async bootstrap debugging

serverless/bootstrap
=> Adds more debugging

lambda/sitemap-batch-processor/handler.pl, serverless/bootstrap
=> Even more debugging for async lambda

cf/everything2-production.json, lambda/Gemfile.lock, lambda/sitemap-batch-dispatcher/handler.pl, lambda/sitemap-batch-processor/handler.pl, ops/lambda-deploy.rb
=> Sitemap generation fully cut over to lambda

cf/everything2-production.json
=> Adds cron entry to call the sitemap generator every day

vagrant/cookbooks/e2cron/recipes/default.rb
=> Crontab now fully moved over to lambda

cf/everything2-production.json, lambda/refresh-rooms/handler.pl
=> Adds lambda handler to replace refreshRoom.pl

serverless/bootstrap
=> Removes echo lines from bootstrap to make perl lambdas less noisy

vagrant/cookbooks/e2cron/recipes/default.rb
=> Remove cron entry for refreshRoom

serverless/Makefile
=> Fixes broken boost dependency

serverless/Makefile
=> Fixes imagemagick makefile

vagrant/cookbooks/e2cron/recipes/default.rb
=> Remove the database backup cron

cf/everything2-production.json, lambda/chatterbox-cleanup/handler.pl
=> Adds lambda function to replace cleanCbox.pl

vagrant/cookbooks/e2cron/recipes/default.rb
=> Removes the cleanCbox element from e2cron

cf/everything2-production.json, lambda/iqm-recalculate/handler.pl, vagrant/cookbooks/e2cron/recipes/default.rb
=> Moves IQM functions to lambda

ecoretool/lib/ecoretool/base.pm
=> Adds debriefing room to nodepack whitelist

nodepack/_data/links.xml, nodepack/room/debriefing_room.xml, nodepack/setting/egg_commands.xml, nodepack/setting/hrstats.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/user/everyone.xml
=> Adds [Debriefing Room]

ecore/Everything/Application.pm, ecore/Everything/Configuration.pm, ecoretool/lib/ecoretool/bootstrap.pm, t/024_clean_old_rooms.t, tools/expirerooms.pl
=> Adds the expirerooms functionality to Everything::Application

cf/everything2-production.json, lambda/cleanup-old-rooms/handler.pl, vagrant/cookbooks/e2cron/recipes/default.rb
=> Adds the expirerooms script functionality to lambda

ecore/Everything/Application.pm, t/025_node_row_reaper.t, tools/reaper.pl
=> Adds the reaper functionality to Everything::Application

cf/everything2-production.json, lambda/writeup-reaper/handler.pl, vagrant/cookbooks/e2cron/recipes/default.rb
=> Moves reaper to lambda, retires cron job

ecore/Everything/DataStash.pm
=> Updates DataStash to have the update_needed method exposed

cf/everything2-production.json
=> Datastash now runs every second

ops/app.json
=> Fixes legacy deployment that would cause an error

ops/deploy-opsworks-build.rb, tools/cloudwatch-agent-installer.rb
=> Adds cloudwatch deb installer

vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb, vagrant/cookbooks/e2engine/templates/default/everything.erb, vagrant/cookbooks/e2engine/templates/default/mod_rewrite.conf.erb
Removes the external log file
Gets rid of a broken m_robots.txt rewrite rule
Eliminates boilerplate 404ing cgi-bin config
Fixes #2111
=> Cleans up several Apache configuration items

vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb, vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Adds single-line JSON for Apache logging

cf/everything2-production.json, serverless/.gitignore, vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds appropriate roles for the servers to push log events

cf/everything2-production.json
=> Updates to the CF in order to facilitate using the SSM agent

cf/everything2-production.json
=> Fix CF typo from get to put for ssm

etc/aws-cloudwatch-agent-config.json
=> Adds the default amazon-cloudwatch-agent config from the wizard

vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes libssl package name

vagrant/cookbooks/e2engine/recipes/default.rb
=> Don't seed the database secret as it doesn't exist anymore

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds the cloudwatch agent script

tools/cloudwatch-agent-installer.rb
=> Fix up script until it dies at the next error

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds collectd for cloudwatch agent

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds nodejs for the development environment for now

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds libcurses to support serverless

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds zlib for serverless

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds pkg-config for serverless

serverless/.gitignore, serverless/Makefile, serverless/deplists/app.json
=> Fixes build to include libexpat

cf/everything2-production.json, vagrant/cookbooks/e2engine/recipes/default.rb, vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb, vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Simplifies the e2 apache configuration

vagrant/cookbooks/e2engine/attributes/default.rb
=> Fixes the apache config to keep servers from eating all available memory

tools/mkswap.sh
=> Adds a swap utility that makes a swapfile

vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes delayed signalling problem

cf/everything2-production.json
=> Increases to 50g from 8g default

lambda/opsworks-reaper/handler.rb
=> Updates the opsworks-reaper to clean up machines that are terminated

cf/everything2-production.json
=> Ups the autoscaling floor to two to handle crashes

ops/deploy.rb, vagrant/cookbooks/e2engine/recipes/default.rb, vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb, vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Move to an included everything conf model instead of conf.d

vagrant/cookbooks/e2engine/recipes/default.rb, vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb
=> Adds in missing security configuration for banners

tools/write_apache_config.rb
=> Adds the apache configuration writer

ecore/Everything/Delegation/container.pm
=> Fixes an SEO issue caused by a typo that somehow passed critic

serverless/deplists/app.json
=> Adds in missing dependency for the Docker build

ecore/Everything/Configuration.pm
=> Fixes the location discovery element for the Docker build

etc/docker-mysql-development.json
=> Adds a stub environment for the docker mysql bootstrap

serverless/deplists/app.json
=> Rearranges B::COW dependencies

serverless/deplists/app.json
=> Updates version of Alien::Build

tools/createdeps.pl
=> Fixes the createdeps makefile wrapper for Docker

docker/devbuild.sh, docker/devclean.sh, docker/e2app/Dockerfile, docker/e2base/Dockerfile, docker/e2db/Dockerfile, docker/e2db/mysqld_dev_wrapper.sh, docker/e2lib/Dockerfile
=> Lots of good work here

docker/devbuild.sh, docker/devclean.sh, docker/e2base/Dockerfile, docker/e2lib/Dockerfile
=> Working docker networking in the dev environment

ecore/Everything/Configuration.pm, etc/development-docker.json
=> Adds config variance for Docker dev environment to use docker network

ecore/Everything/Configuration.pm
=> Adds configuration for docker

vagrant/cookbooks/e2engine/templates/default/apache2.conf.erb
=> Adds PassEnv to the config

vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Updates the Apache config

vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Reverts bad change and puts in real fix

lambda/opsworks-reaper/handler.rb
=> Adds lambda code to clean up reaped opsworks instances

serverless/deplists/app.json
=> Fixes the UTF8 strict module dependency for ecoretool

ecoretool/ecoretool.pl, nodepack/_data/links.xml, nodepack/_data/nodegroup.xml, nodepack/dbtable/nodegroup.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/bounty_order.xml, nodepack/setting/egg_commands.xml, nodepack/setting/hrstats.xml, nodepack/setting/outlaws.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/iron_noder_progress.xml, nodepack/user/edb.xml, nodepack/user/everyone.xml
=> Changes nodegroup rank table definition

docker/e2base/Dockerfile
=> Fixes logging directory for e2base

vagrant/cookbooks/e2engine/templates/default/everything.erb
=> Fixes double-escaping problem by moving template into template builder

cf/everything2-production.json
=> Adds a new event bus for uninitialized values

ecore/Everything/Application.pm
=> Different bus for different folks

ecore/Everything/Application.pm, ecore/Everything/Page/sign_up.pm
=> Fixes a problem with signup where IPs weren't getting logged

ecore/Everything/Delegation/nodelet.pm
=> Fixes CGI warning in everything developer

ecore/Everything/Delegation/document.pm
=> Fix scalar warning in CGI::Param

ecore/Everything/Delegation/nodelet.pm
=> Fixes argument isn't numeric warning

nodepack/superdoc/jaybonci's_sandbox.xml, nodepack/ticker/user_search_xml_ticker_ii.xml
=> Fixes User Search XML Ticker II error

ecore/Everything/Delegation/htmlcode.pm
=> Fixes another CGI::Param warning

cf/everything2-production.json, docker/buildspec.yml
=> Initial work for the docker builder

cf/everything2-production.json, docker/buildspec.yml
=> Fixes some buildspec items for e2lib

cf/everything2-production.json, docker/buildspec.yml, docker/e2base/Dockerfile, ecore/Everything.pm, tools/buildcache.rb
=> Adds buildcache

docker/buildspec.yml
=> Why change your mind when you can chmod?

docker/buildspec.yml
=> Installs the gem dependencies into the environment

.buildcache/.gitignore, cf/everything2-production.json, tools/buildcache.rb
=> Adds buildcache dir

vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes the vagrant version to not use the git protocol

ecore/Everything/NodeBase.pm
=> Backs out the nodegroup emulation code

ecore/Everything/Delegation/htmlcode.pm
=> Fixes CGI::Param issue

nodepack/_data/nodegroup.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/page_of_cool.xml, nodepack/user/everyone.xml
=> Fixes a problem now that exeds is empty

ecore/Everything/Delegation/document.pm
=> Delegates page of cool out of the database

ecore/Everything/HTML.pm
=> Fixes problem with CGI::param in list context

tools/user_data_backup.pl
=> Adds the user data backup script

docker/buildspec.yml
=> Fixes the docker build to add conditional support

docker/buildspec.yml, tools/buildcache.rb
=> Adds conditional checks to buildspec.yml

docker/buildspec.yml
Permissions are being stripped by the code packager
Fixes #2296
=> Makes buildcache.rb chmod +x in the yml

docker/buildspec.yml, tools/buildcache.rb
=> Remembers to do the right thing in the cloud version of the buildcache

docker/buildspec.yml
=> And found a typo!

ecore/Everything/Delegation/opcode.pm
=> Closes CGI::param issue

ecore/Everything/Application.pm
=> Fixes a latent error

ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlpage.pm
=> Delegates the code in [News Archive]

ecore/Everything/Delegation/document.pm
=> Delegates [ipfrom]

nodepack/superdoc/ipfrom.xml
=> Removes code from [ipfrom]

cf/everything2-production.json
=> Adds the cluster definition

ecore/Everything/Delegation/document.pm
Several cleanups along the way
Fixes #2153
=> Delegates [Your Ignore List]

ecore/Everything/Configuration.pm, t/011_configuration.t, t/testdata/config_2.json, t/testdata/config_3.json, tools/conftest.pl
=> Eliminates basedir as a configuration item

ecore/Everything/Delegation/document.pm
=> Fixes Everything's Obscure Writeups

nodepack/superdoc/everything's_obscure_writeups.xml
=> Removes code from [Everything's Obscure Writeups]

ecore/Everything/Delegation/document.pm
=> Delegates [Silver Trinkets]

nodepack/superdoc/silver_trinkets.xml
=> Removes the code from [Silver Trinkets]

ecore/Everything/Delegation/htmlpage.pm
=> Fixes sql error in choosetheme, a feature I don't really understand

docker/e2app/Dockerfile
=> Adds -f to softlinks

docker/buildspec.yml
=> Updates for differential build

ecore/Everything/Application.pm
=> Fixes the newnodes functionality if you aren't an editor

ecore/Everything/Delegation/document.pm
=> Adds something silly to the delegation

ecore/Everything/Application.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Page/ipfrom.pm, ecore/Everything/Request.pm, templates/pages/ipfrom.mc
Does some stuff to make IP issues easier to debug
Fixes #2368
=> Pushes [ipfrom] into a template

templates/nodelets/new_writeups.mi
=> Man I love templates

ecore/Everything/Application.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Page/everything_s_obscure_writeups.pm, templates/pages/everything_s_obscure_writeups.mc
=> Adds [Everything's Obscure Writeups] to the templates

ecore/Everything/Delegation/document.pm
=> Delegates [Your Gravatar]

nodepack/_data/nodegroup.xml, nodepack/superdoc/your_gravatar.xml
=> Removes code from Your Gravatar

ecore/Everything/Delegation/document.pm, ecore/Everything/Node/user.pm, ecore/Everything/Page/your_gravatar.pm, templates/pages/your_gravatar.mc
=> Templatize [Your Gravatar]

ecore/Everything/Page/wharfinger_s_linebreaker.pm, templates/pages/wharfinger_s_linebreaker.mc
=> Templatize [Wharfinger's Linebreaker]

ecore/Everything/Page/is_it_christmas_yet.pm
=> Adds a template for [is it christmas yet?]

nodepack/superdoc/is_it_christmas_yet_.xml
=> Remove code from christmas node

ecore/Everything/Page/online_only_msg.pm, templates/pages/online_only_msg.mc
=> Adds a document node to the templates folder

nodepack/superdoc/online_only__msg.xml
=> Removes HTML from a documentation superdoc

ecore/Everything/Page/is_it_halloween_yet.pm
Newline cleanup in xmas
Fixes #2396
=> Direct to template for halloween

nodepack/superdoc/is_it_halloween_yet_.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Removes the code from halloween

cf/everything2-production.json
=> Adjusts the lambda functions to save money

cf/everything2-production.json
=> New logging bucket for ELB, logs flowing nicely

docker/e2base/Dockerfile, vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes odd quirk of apache2 on debian without a log line

vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes apache log ownership problem

docker/buildspec.yml
=> Pull the dependencies before build for starters

docker/buildspec.yml
=> Specifies account-specific ECR on docker pulls

cf/everything2-production.json
=> Adds ECR lifecycle

docker/e2app/Dockerfile, docker/e2app/apache2_wrapper.rb, docker/e2base/Dockerfile
=> Updates builds to download secrets on startup

ecore/Everything/Configuration.pm
=> Removes backup from E::Config

cf/everything2-production.json
=> Removes the old backup bucket as everything is fully cloud now

ecore/Everything/Delegation/opcode.pm
=> Kills a warning/security problem in publishdraft

ecore/Everything/Application.pm
=> Fixes some module use issues in E::A

ecore/Everything/Page/is_it_new_year_s_day_yet.pm, ecore/Everything/Page/is_it_new_year_s_eve_yet.pm
=> Templatize NYE/NYD docs

nodepack/oppressor_superdoc/everything2_user_relations__e2contact_and_chanops.xml, nodepack/setting/hrstats.xml, nodepack/superdoc/is_it_new_year's_day_yet_.xml, nodepack/superdoc/is_it_new_year's_eve_yet_.xml, nodepack/superdoc/wheel_of_surprise.xml, nodepack/user/everyone.xml, nodepack/user/klaproth.xml
=> Removes code from the NYE/NYD nodes

cf/everything2-production.json, lambda/nodepack-builder/handler.pl, nodepack/superdoc/jaybonci's_sandbox.xml, ops/nodepack-refresh.rb
I no longer need server access!
Fixes #2441
=> Creates a nodepack updating lambda function

ecore/Everything/Page/piercisms_generator.pm, templates/pages/piercisms_generator.mc
=> Straight to template: [Piercisms Generator]

nodepack/htmlcode/typemenu.xml
=> Deletes stray htmlcode

ecore/Everything/Delegation/htmlcode.pm
=> Removes typeMenu

ecore/Everything/Delegation/document.pm
=> Delegates [Superbless]

ecore/Everything/Delegation/document.pm
=> Delegates [Spam Cannon]

ecore/Everything/Delegation/document.pm
=> Delegating [Pit of Abomination]

nodepack/superdoc/pit_of_abomination.xml
=> Removes the code from [Pit of Abomination]

ecore/Everything/Delegation/document.pm, tools/seeds.pl
Also fixes a problem with the seeds generator and lasttime timestamps being invalid
Fixes #2478
=> Delegates [Level Distribution]

ecore/Everything/Delegation/document.pm
=> Delegates [Nodeshells]

nodepack/superdoc/nodeshells.xml
=> Removes code from [Nodeshells]

nodepack/superdoc/login.xml
=> Fixes a server error on [login]

ecore/Everything/Delegation/document.pm
=> Delegates [Your Nodeshells]

ecore/Everything/Application.pm, ecore/Everything/Page/your_nodeshells.pm, templates/helpers/username_selector.mi, templates/pages/your_nodeshells.mc
=> [Your nodeshells] now as a convenient template

ecore/Everything/Application.pm, ecore/Everything/Node/e2node.pm, templates/pages/your_nodeshells.mc
=> Merges the two [Your Nodeshells] nodes

ecore/Everything/Delegation/document.pm, ecore/Everything/Security/StaffOnly.pm
=> Delegates [Recent Node Notes]

ecore/Everything/Configuration.pm, ecore/Everything/Node/draft.pm, ecore/Everything/NodeBase.pm, ecore/Everything/Page/recent_node_notes.pm, ecore/Everything/PermissionResult/PermissionDenied.pm, ecore/Everything/Security/StaffOnly.pm, ecore/Everything/Timestamp.pm, templates/helpers/pagination.mi, templates/pages/recent_node_notes.mc
=> Adds template for [Recent Node Notes]

nodepack/superdoc/recent_node_notes.xml, nodepack/user/klaproth.xml
We begin to get rid of oppressor/restricted superdocs
Fixes #2524
=> Changes the type of a [recent_node_notes]

nodepack/oppressor_superdoc/security_monitor.xml
=> Fixes security monitor

ecore/Everything/Delegation/document.pm, ecore/Everything/Page/nodeshells.pm, templates/pages/nodeshells.mc
=> Move [nodeshells] to a template-driven node

ecore/Everything/Delegation/document.pm
=> Delegates [Manna From Heaven]

ecore/Everything/Page/manna_from_heaven.pm, templates/helpers/linknodetitle.mi, templates/pages/manna_from_heaven.mc
Fixes a linknodetitle template bug
Fixes #2536
=> Adds the page for [manna from heaven]

nodepack/superdoc/manna_from_heaven.xml
=> Changes the type of manna_from_heaven

nodepack/oppressor_superdoc/foetid_den.xml
=> Removes empty [oppressor_superdoc]

ecore/Everything/Delegation/document.pm
=> Delegates [content reports]

nodepack/oppressor_superdoc/everything2_account_lock_ledger.xml
=> Removes old dead document

nodepack/oppressor_superdoc/stupid_ads_must_die!.xml
=> Deletes [Stupid Ads Must Die]

nodepack/oppressor_superdoc/recent_title_edits.xml
=> Deletes an empty, ancient node

cf/everything2-production.json
=> Adds the cloudformation templates which create the ECS baseline for E2

cf/everything2-production.json
=> Adds the right permissions for the docker build

cf/everything2-production.json, docker/buildspec.yml
=> Tries some docker settings

docker/buildspec.yml
=> Try a new docker build tag strategy

nodepack/oppressor_superdoc/your_insured_writeups.xml, nodepack/setting/hrstats.xml, nodepack/superdoc/everything's_biggest_stars.xml, nodepack/user/webster_1913.xml
=> Remove code from [Your Insured Writeups]

ecore/Everything/Delegation/htmlcode.pm, templates/helpers/googleads.mi
=> Uses asynchronous ads

nodepack/setting/hrstats.xml, nodepack/superdoc/your_insured_writeups.xml
=> Change the type of [Your insured writeups]

docker/devclean.sh, ecore/Everything/Delegation/document.pm
=> Removes the legacy delegation code frmo [Your insured writeups]

docker/e2app/apache2_wrapper.rb
=> Changes the apache wrapper to cat the error log on startup if necessary

docker/buildspec.yml
=> Pulls the buildcache for the CodeBuild script

etc/templates/everything.erb
=> Fixes PerlPassEnv warning

cf/everything2-production.json
=> Adds the fargate task execution role

docker/e2app/apache2_wrapper.rb
=> Debugging information to get into the Fargate messages

docker/e2app/apache2_wrapper.rb
=> Adds debugging information to the ECS role

etc/templates/apache2.conf.erb, etc/templates/everything.erb
=> Probably fixes Fargate

docker/e2app/apache2_wrapper.rb, etc/templates/apache2.conf.erb, etc/templates/everything.erb
=> Try passing in the region

ecore/Everything/Configuration.pm
=> Adds support for AWS_DEFAULT_REGION

cf/everything2-production.json
=> Adds a health check for the containers

cf/everything2-production.json
=> Creates the cron baseline to start to eliminate lambda

cf/everything2-production.json, ops/cron-runner.rb
=> Adds cron debugging

cf/everything2-production.json, cron/cron_clean_cbox.pl, ops/cron-runner.rb
=> Adds to FARGATE_SPOT, fixes perl invocation issues

cf/everything2-production.json
=> Adds layer caching to CodeBuild

cf/everything2-production.json, cron/cron_generate_sitemap.pl
=> Add in debugging stuff to the s3 elements

cron/cron_generate_sitemap.pl
=> More sitemap debugging

cron/cron_generate_sitemap.pl, docker/e2app/Dockerfile
=> Optimize the build and fix a typo in sitemap

cron/cron_generate_sitemap.pl
=> Moves to the full cronjob now that debugging is working

cron/cron_datastash.pl
=> Moved the datastash tool to a cron-ready job

cf/everything2-production.json
=> Adds the datastash cron job, disables the lambda one

cron/cron_datastash.pl, ops/cron-runner.rb
=> Separates out the lengthy datastash elements

cron/cron_iqm_recalculate.pl
=> Places cron script for global IQM recalc

cron/cron_refresh_rooms.pl
=> Moves the refresh rooms cron job to the organized directory

cron/cron_clean_old_rooms.pl
=> Adds the room cleanup script to the proper cron directory

cron/cron_writeup_reaper.pl, tools/reaper.pl
=> Puts the writeup reaper script into position

README.md, jobs/job_nodepack_builder.pl
Adds new nodepack builder job based on the lambda
Fixes #2671
=> Updates README.md

jobs/job_nodepack_builder.pl, ops/nodepack-refresh.rb
Changes the wrapper to be ECS aware
Fixes #2673
=> Updates the ECS job to call the right perl binary

jobs/job_nodepack_builder.pl
=> Fixes directory in ecoretool invocation

cf/everything2-production.json
=> Updates mysql to the newest minor version

serverless/deplists/app.json
=> Pulls out HTML::Tiny

ecore/Everything/Application.pm, ecore/Everything/Form/field_hashing.pm, ecore/Everything/Page/sign_up.pm, templates/pages/sign_up.mc
=> Overhauls the sign up page

ecore/Everything/Delegation/htmlcode.pm
=> Fixes busted lede type

ecore/Everything/Delegation/htmlcode.pm
=> Lede still doesn't work

docker/e2app/Dockerfile, ecore/Everything/Configuration.pm, lambda/cicd-zips-puller/handler.rb
=> Fix codebuild failure

nodepack/restricted_superdoc/the_old_hooked_pole.xml, nodepack/setting/hrstats.xml, nodepack/user/virgil.xml
=> Old Hooked Pole fixes

ecore/Everything/Page/sign_up.pm
=> Fixes the recaptcha perl problem

ecore/Everything/Page/sign_up.pm
=> Adds some debugging to recaptcha

docker/e2app/apache2_wrapper.rb, ecore/Everything/Page/sign_up.pm
Also fixes another problem in sign_up
Fixes #2704
=> Fixes docker secret download (maybe)

ecore/Everything/Page/sign_up.pm
Removes debugging stuff from [sign up]
Fixes #2706
=> Removes debugging stuff from [sign up]

ecore/Everything/Delegation/htmlpage.pm
=> Squashes a bad theme input parameter

.github/workflows/push-to-codecommit.yml, cf/everything2-production.json, ops/.gitignore, ops/create-github-credential.rb
=> Adds beginning of codecommit integration

.github/workflows/push-to-codecommit.yml
=> Adds the hardcoded action

.github/workflows/push-to-codecommit.yml
=> Fixes github workflow yml

.github/workflows/push-to-codecommit.yml
=> Fixes github workflow to use ssh

.github/workflows/push-to-codecommit.yml
=> Try some path magic, squash junky errors

.github/workflows/push-to-codecommit.yml
=> Trying new git strategies

.github/workflows/push-to-codecommit.yml
=> Only pushes branches; I don't use tags anyway

ecore/Everything/Delegation/document.pm
=> Delegates the code for [Topic Archive]

.github/workflows/push-to-codecommit.yml
=> Try --mirror instead of --all

.github/workflows/push-to-codecommit.yml
=> Tries --force

.github/workflows/push-to-codecommit.yml, nodepack/superdoc/topic_archive.xml
Does something with fetch depth to try and fix the github workflow
Fixes #2727
=> Removes code from [Topic Archive]

.github/workflows/push-to-codecommit.yml
=> Get the yaml syntax right

cf/everything2-production.json, docker/e2app/Dockerfile
=> Adds in transition elements to CodeCommit for CodeBuild

serverless/deplists/app.json
=> Remove Authen::SASL

cf/everything2-production.json, docker/buildspec.yml, ops/run-codebuild.rb
Fixes deployment script typo
Adds terser to build environment
Fixes #2743
=> Creates a new asset bucket

cf/everything2-production.json, docker/buildspec.yml, tools/asset_pipeline.rb
=> Builds the new asset pipeline

docker/buildspec.yml
Don't push a broken build
Fixes #2749
=> Adds s3 elements to the build pipeline

ecore/Everything/Delegation/htmlpage.pm
=> Fix displaytype=serve to get information about the stylesheet

ecore/Everything/Delegation/htmlpage.pm
=> Fixes theme previewing as I clean up the display code

ecore/Everything/Application.pm, ecore/Everything/Delegation/container.pm, ecore/Everything/Node/stylesheet.pm, ecore/Everything/Node/user.pm
=> Only allow supported stylesheets in the main display areas

ecore/Everything/Delegation/htmlpage.pm
=> Adds usercount to each stylesheet page

AUTHORS.md
=> Credits CSS authors in the main file

nodepack/superdoc/nothing_found.xml
=> Fixes problems with the tinopener

cf/everything2-production.json
=> Remove the webheads ability to upload JSCSS files

ecore/Everything/HTML.pm
=> Fixes clickjacking by adding sameorigin frame restriction in HTTP

nodepack/superdoc/theme_nirvana.xml
=> Fixes server error in [Theme Nirvana]

templates/helpers/linknode.mi, templates/pages/your_nodeshells.mc
Thanks to raincomplex
Fixes #2594
=> Fixes to [Your Nodeshells]

ecore/Everything/Application.pm
=> Adds a parameter for sheet management

nodepack/_data/nodeparam.xml, nodepack/setting/hrstats.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Marks certain stylesheets as dependent

ecore/Everything/Application.pm, ecore/Everything/Configuration.pm, ecore/Everything/Controller.pm, ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Node/helper/s3.pm, ecore/Everything/Node/jscript.pm, ecore/Everything/Node/stylesheet.pm, etc/development-docker.json, etc/development.json, templates/zen.mc, tools/asset_pipeline.rb
=> New javascript asset pipeline

ecore/Everything/Configuration.pm, nodepack/superdoc/settings.xml, t/011_configuration.t, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes the stylesheet fix level from the configuration

nodepack/stylesheet/dim_jukka_emulation.xml, nodepack/stylesheet/jukka_emulation.xml, nodepack/superdoc/text_formatter.xml, www/css/1855548.css, www/css/1997697.css
=> Removes styledef references in a bunch of places

ecore/Everything/Delegation/document.pm, www/js/1874924.js
=> Pulls the [E2 Rot13 Encoder] javascript into assets

nodepack/_data/nodeparam.xml, nodepack/setting/hrstats.xml
=> Remove the supplemental javascript from the quote server

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
=> Removes supplemental_javascript feature

nodepack/jscript/autoformat_javascript.xml, www/js/2069739.js
=> Removes the autoformat javascript which has been consolidated

www/js/2115138.js
It still appears to have some corner cases
Fixes #2874
=> Fixes the mixed content warning in [My Chatterlight]

nodepack/fullpage/my_chatterlight.xml, nodepack/jscript/jstest.xml, www/js/2115138.js
=> Adjusts my chatterlight to be within the mainline for javascript

nodepack/jscript/message_inbox_javascript.xml, nodepack/superdoc/message_inbox_2.xml, www/js/2069795.js
=> Removes extra javascript inclusion from [Message Inbox 2]

www/js/1874924.js
=> Cleans out unused mi2 functions

nodepack/superdoc/message_inbox_2.xml
=> Fixes CGI param in list context in MI2

www/js/1874924.js
=> All one javascript file (except tinymce)

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/googleanalytics.xml, nodepack/setting/hrstats.xml, nodepack/setting/penny_jar.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Removes the [googleanalytics] htmlcode

docker/buildspec.yml, tools/asset_pipeline.rb
Also includes componentry for brotli and deflate
Fixes #2906
=> Changes the asset pipeline to use path-based assets

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/linkjavascript.xml
=> Removes [linkjavascript]

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/maintenance.pm, ecore/Everything/HTML.pm, nodepack/maintenance/jscript_maintenance_create.xml
=> Removes [JScript Maintenance Create]

AUTHORS.md
=> Credit all of the patchers before we delete the nodetype

ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/maintenance.pm, ecore/Everything/Delegation/nodelet.pm, ecore/Everything/Delegation/opcode.pm
=> Removes the zenMobileTabs code hooks

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/zenmobiletabs.xml
=> Removes [zenMobileTabs]

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Removes the last vestiges of isMobile()

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm
Removes some unneeded functionality
Fixes #2934
=> Changes to the Everything Developer nodelet

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/ednsection_cgiparam.xml, nodepack/htmlcode/ednsection_patches.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Removes two unused ednsections

ecore/Everything/Configuration.pm, ecore/Everything/Controller.pm, ecore/Everything/DataStash/frontpagenews.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/maintenance.pm, ecore/Everything/Form/field_hashing.pm, ecore/Everything/Link.pm, ecore/Everything/Page/other_users_xml_ticker.pm, ecore/Everything/Page/recent_node_notes.pm, ecore/Everything/Page/your_ignore_list.pm, ecore/Everything/ect/dbtable.pm, tools/critic.pl
Cleans up some whitespace while I am there
Fixes #2948
=> Makes perl critic work locally

ecore/Everything/Delegation/htmlcode.pm
=> Fixes a cgi param warning

react/components/Nodelets/VitalsNodelet.js
=> Adds CoC to the Vitals Nodelet

react/components/LinkNodeTitle.js
=> Fixes encoding issue with Apache routing in the new vitals nodelet

ecore/Everything/Delegation/nodelet.pm
=> Fixes some broken glass in the Statistics Nodelet

ecore/Everything/Delegation/nodelet.pm, nodepack/_data/nodegroup.xml, nodepack/nodelet/node_statistics.xml, nodepack/setting/hrstats.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Deletes the [node status] nodelet

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, nodepack/fullpage/chatterlight.xml, nodepack/setting/hrstats.xml, react/components/Portals/NodeletPortal.js, tools/db.pl
I apologize for the horrible fullpage hack
Fixes the database access script in Docker
Also a bug where we are abusing non-strict mode in messages
Fixes #2890
Fixes #2978
=> Fixes chatterlight javascript issue.

ecore/Everything/Application.pm
=> Reverses the order of news items in Developer Nodelet

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/ednsection_edev.xml, nodepack/htmlcode/ednsection_globals.xml, nodepack/htmlcode/ednsection_util.xml
=> Removes ednsection_*

cf/everything2-production.json
=> Adds ulimit stuff for apachectl

cf/everything2-production.json
=> Bandaids the ELB health check

nodepack/fullpage/guest_front_page.xml, nodepack/setting/hrstats.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Adding in the React root to [Guest Front Page]

react/components/LinkNode.js, tools/seeds.pl
=> Fixes generic linkNode issue with writeups that have a slash

react/components/LinkNode.js, tools/seeds.pl
=> Adds ampersand to double-commit issue

docker/e2app/Dockerfile, ops/run-codebuild.rb
Also fixes the codebuild script to launch 2 instances
Fixes #2986
=> Updates NPM to the modern stable version

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, ecore/Everything/HTML.pm, ecore/Everything/Node.pm, ecore/Everything/Request.pm, etc/templates/everything.erb, tools/seeds.pl
=> Fix CGI.pm to accept utf-8

ecore/Everything/API/newwriteups.pm, ecore/Everything/Application.pm, ecore/Everything/Controller.pm, ecore/Everything/Delegation/htmlcode.pm, react/components/NewWriteupsEntry.js
Updates the API to include it
Fixes #3001
=> Makes the CSS changes for hasvoted

react/components/E2ReactRoot.js, react/components/Nodelets/Vitals.js
Runs Once per minute
Also cleans up unnecessary key
=> Adds a new writeups refresh capability

docker/e2db/mysqld_dev_wrapper.sh
=> Adds a timeout value to the mysql configuration for development

cf/everything2-production.json
=> Allows for athena to debug ELB logs

react/components/EditorHideWriteup.js
=> Fixes the editor hide notification formatting

etc/templates/apache2.conf.erb
=> Adds a healthcheck log to aid in debugging

etc/templates/apache2.conf.erb
=> Change to health log format

etc/templates/apache2.conf.erb, etc/templates/everything.erb
=> Increase logging in production

etc/templates/apache2.conf.erb
=> Increase loglevel to debug

tools/generate-self-signed-cert.rb
=> Fixes self-signed certificate SANs

etc/templates/apache2.conf.erb
=> Changes virtualhost ordering

www/api/index.pl
=> Removes junk log entry

ecore/Everything/HTML.pm
This doesn't reproduce in development, which is troubling
Fixes #3032
=> Does encoding for gzip-likes

etc/templates/apache2.conf.erb
=> Shuts off the healthcheck log

cf/everything2-production.json, nodepack/setting/hrstats.xml, nodepack/superdoc/jaybonci's_sandbox.xml
=> Removes ELB bandaid

ecore/Everything/Delegation/htmlpage.pm
I really hate this code
Fixes #2990
=> Fixes broken room permissions

ecore/Everything/Application.pm, ecore/Everything/Controller.pm, ecore/Everything/HTML.pm, ecore/Everything/Node.pm, ecore/Everything/Router.pm, templates/zen.mc
=> Fixes [raincomplex]'s Your Nodeshells page

react/components/E2ReactRoot.js
=> Fixes condition where New Writeups would blank on a bad fetch

serverless/deplists/app.json
=> Removes XML::RSS as we don't need it

ecore/Everything/Page/sign_up.pm, nodepack/mail/welcome_to_everything2.xml, nodepack/setting/hrstats.xml, nodepack/setting/room_topics.xml, nodepack/user/everyone.xml, nodepack/user/webster_1913.xml
=> Tries to fix [Sign Up]

ecore/Everything.pm, ecore/Everything/APIRouter.pm, ecore/Everything/Configuration.pm, ecore/Everything/HTML.pm, etc/templates/apache2.conf.erb, etc/templates/everything.erb, t/legacy/011_configuration.t, t/testdata/config_2.json, t/testdata/config_3.json, www/maintenance.html
=> Fixes the maintenance message

ecore/Everything/Router.pm
Really, really obvious in retrospect
Fixes #3053
=> Fixes the API encoding

docker/devbuild.sh, docker/e2app/apache2_wrapper.rb, ecore/Everything/Configuration.pm, etc/templates/apache2.conf.erb, etc/templates/everything.erb
cleans up some logging messages
Fixes #3056
=> Renames the E2DOCKER variable to E2_DOCKER

docker/devbuild.sh, ecore/Everything/Configuration.pm, etc/development-docker.json, etc/templates/apache2.conf.erb, etc/templates/everything.erb
=> Allow e2_dbserv to be a docker env variable so CF can manage connection

cf/everything2-production.json, docker/devbuild.sh, etc/docker-mysql-development.json, etc/production.json
=> Makes E2 more cloud native by having the environment configure the DB

cf/everything2-production.json, etc/templates/apache2.conf.erb
=> Fix the loglevel

cf/everything2-production.json
=> Removes old RDS role that ECS doesn't use

cf/everything2-production.json
=> Updates DB to 5.7.39

cf/everything2-production.json, cf/stack-policy.json
This is the best we can do for now
Fixes #3062
=> There's a flaw with RDS about scalable storage and CloudFormation

nodepack/_data/links.xml, nodepack/setting/hrstats.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/iron_noder_progress.xml, nodepack/superdoc/jaybonci's_sandbox.xml, nodepack/superdoc/node_backup.xml, nodepack/user/everyone.xml
=> Fixes [Node Backup], also adds a snapshot of changed nodes

docker/buildspec.yml
=> Updates nodejs to 16.20 in AWS codebuild

nodepack/superdocnolinks/e2_color_toy.xml
=> Fixes [E2 Color Toy]

react/components/LinkNode.js
=> Changes to the react code to workaround bad CVE fix in HTTPD

docker/e2app/Dockerfile, serverless/deplists/app.json
=> Upgrades Ubuntu

etc/templates/everything.erb, react/components/LinkNode.js
=> Fixes mod_rewrite issue

docker/e2app/Dockerfile
=> Fixes thing that bugs the Amazon version of Docker (but not my local)

docker/e2app/Dockerfile, tools/asset_pipeline.rb
=> Fixes the asset pipeline and associated test entities

tools/asset_pipeline.rb
=> Fixes the asset pipeline builds

docker/e2app/Dockerfile
=> Fixes problem with npm path in AWS CodeBuild

docker/buildspec.yml
=> Fixes the node installation version

cf/everything2-production.json
=> Fixes Amazon Linux version in CodeBuild

README.md, nodepack/restricted_superdoc/node_cloner.xml, nodepack/setting/hrstats.xml, nodepack/superdoc/node_backup_2.xml
=> Fixes a warning in Node Cloner

nodepack/restricted_superdoc/sql_prompt.xml
=> Adds root to SQL Prompt and takes out older users

docker/db, ecore/Everything/Delegation/nodelet.pm, tools/seeds.pl
Adds ed cools to the developer database
Fixes a weird coding error in [Recommended Reading]
=> Fixes a typo in the db script

react/components/LinkNode.js, tools/seeds.pl
Turns out I know react a lot better than I did 6 months ago.
Fixes #3150
Fixes #3077
=> Fixes new writeups encoding regression

cf/everything2-production.json
=> Rotates the RDS cert

cf/everything2-production.json
Migrated to ARM processor
Fixes #3135
=> Upgrades database to mysql 8.0

serverless/deplists/app.json
=> Upgrades DBD::Mysql to get rid of OPT Reconnect log spam

ecore/Everything/Application.pm, react/components/LinkNode.js, tools/seeds.pl
Adds seeds info
Updates cloudwatch elements
Fixes #3138
=> Fixes semicolon in New Writeups

ecore/Everything/Delegation/htmlcode.pm
=> Fixed static_javascript warning for developers

cf/everything2-production.json
=> Update max scaling depth

react/components/E2ReactRoot.js, react/components/ErrorBoundary.js
=> Adds ErrorBoundary class

ecore/Everything/Delegation/htmlcode.pm
=> Adds password helper elements to the login form

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, ecore/Everything/Node/writeup.pm, react/components/E2ReactRoot.js, react/components/Nodelets/NewLogs.js, react/components/Nodelets/NewWriteups.js, react/components/Portals/NewLogsPortal.js, tools/seeds.pl
This also helps to free up and eliminate some of the snarlier and old code around display and the older newwriteups structure
Fixes #3154
=> Moves [New Logs] over to React

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/zenwriteups.xml, react/components/Nodelets/NewLogs.js
=> Deletes [zenwriteups] to make way for more data cleanup

ecore/Everything/API/hidewriteups.pm, ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/maintenance.pm, ecore/Everything/Delegation/opcode.pm, react/components/Nodelets/NewLogs.js
=> Remove the need to reference the hard-to-grep 'update New Writeups data'

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/update_new_writeups_data.xml
=> Removes [update New Writeups data]

ecore/Everything/DataStash/newwriteups.pm
This will allow the namespace cutover and code reduction
Fixes #3162
=> Merges newwriteups and newwriteups2

nodepack/datastash/newwriteups2.xml
=> Removes the newwriteups2 stash, completing the cutover

ecore/Everything/Application.pm, ecore/Everything/Controller.pm, ecore/Everything/Delegation/htmlcode.pm
=> Fixes E2 variable creation between templates and legacy

ecore/Everything/Application.pm, ecore/Everything/Delegation/nodelet.pm, react/components/E2ReactRoot.js, react/components/Nodelets/RandomNodes.js, react/components/Portals/RandomNodesPortal.js, templates/nodelets/random_nodes.mi
=> Moves Random Nodes to React

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/minilogin.xml
=> Removes [minilogin]

cf/everything2-production.json
=> Adds RDS performance insights

ecore/Everything/Controller.pm, ecore/Everything/Form/field_hashing.pm
=> Fixes odd error in CGI in [Sign Up]

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
=> Closes up a bunch of application warnings to clean clutter

ecore/Everything/Application.pm
=> Fixes uninitialized value in compression adjudication

ecore/Everything/Application.pm
=> DRYs up the code and encodes even if no compression

ecore/Everything/Router.pm
=> Fix double-encode of JSON after encoding update

ecore/Everything/Application.pm
=> Fixes uninitialized value in concat for bots

tools/asset_pipeline.rb
=> Update asset_pipeline script to account for favicon as x-icon

ecore/Everything/Delegation/document.pm
=> Unintialized values clogging up the logs

tools/asset_pipeline.rb
=> Fixes asset pipeline typo

ecore/Everything/Application.pm
=> Tries to refix best compression

ecore/Everything/Configuration.pm, etc/templates/apache2.conf.erb
=> Tune server parameters

ecore/Everything/Delegation/htmlcode.pm
=> Fixes to htmlcode to clean up warnings

nodepack/restricted_superdoc/sql_prompt.xml, nodepack/setting/hrstats.xml
=> Fixes SQL prompt ordering

cf/everything2-production.json
=> Mysql error and slow logs

docker/e2db/mysqld_dev_wrapper.sh
=> Fixes permissions on mysql bootstrap script for dev

ecore/Everything/NodeBase.pm
=> Update to TLS connection for mysql

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/opcode.pm
=> Removes calls to logWarning

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/logwarning.xml
=> Removes logWarning

ecore/Everything/Delegation/opcode.pm
=> Fixes uninitialized value warning in opmessage

docker/devbuild.sh, docker/devdbbuild.sh, ecore/Everything/Delegation/htmlpage.pm, tools/seeds.pl
Adds a node_forward to the seeds file
Fixes #3211
=> Closes up uninitialized value warning

react/components/LinkNode.js, tools/seeds.pl
=> Properly double-escapes question marks in React

.vscode/tasks.json, ecore/Everything/Delegation/document.pm
=> Remove an instance of [show content] from the db

ecore/Everything.pm, ecore/Everything/Application.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Node/writeup.pm, ecore/Everything/NodeBase.pm, ecore/Everything/Page/sign_up.pm, react/components/NewWriteupsEntry.js, serverless/deplists/app.json, t/run.pl, tools/seeds.pl
Updates a few dependencies
Kills off all active perlcritic warnings
Fixes #3236
=> Removes [show content] from [Writeups by Type]

ecore/Everything.pm, ecore/Everything/HTML.pm
=> Revered SIG change in AWS warn handlers

ecore/Everything/Delegation/htmlpage.pm
=> Fixes uninit value warning in htmlpage.pm

cf/everything2-production.json, docker/buildspec.yml
=> Migrate to a variable in the ECR Repository

cf/everything2-production.json, docker/buildspec.yml, ecore/Everything/Application.pm, ecore/Everything/Configuration.pm, react/components/E2ReactRoot.js, react/components/Nodelets/Developer.js
Adds processor arch support
Fixes #3174
=> Creates ARM build environment

cf/everything2-production.json, debian/build_modern_apache.sh, ecore/Everything/NodeCache.pm
Cleans up some whitespace stuff in Nodebase.pm
Also guesses the right arm value for node
Fixes #3246
=> Update build_modern_apache to be arch-neutral

ecore/Everything/Application.pm, ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/maintenance.pm, ecore/Everything/Delegation/nodelet.pm, serverless/deplists/app.json
also uses HTML::Defang to close tags
Cleans out a lot of old, unneeded symbol mapping
Fixes #3249
=> Moves HTML cleaning to HTML::Scrubber

cf/everything2-production.json, etc/templates/apache2.conf.erb
Stops logging CodeBuild to CloudWatch
Fixes #3255
=> Tunes apache to not kill itself

cf/everything2-production.json, etc/templates/apache2.conf.erb
=> Revert the breaking change to CodeBuild

ecore/Everything/Configuration.pm
=> Increases nodecache size up

ecore/Everything/Application.pm, ecore/Everything/DataStash/randomnodes.pm, ecore/Everything/HTML.pm
=> Refactors Random Nodes generator for speed

cf/everything2-production.json, ops/run-codebuild.rb
=> Cuts over to ARM. Confirmed working

ecoretool/lib/ecoretool/export.pm, ops/nodepack-refresh.rb
S3 can't have files with single-quote
Puts ecoretool on fargate provider for ARM
Fixes #3261
=> First part of a fix to ecoretool

ecoretool/lib/ecoretool/export.pm
=> Fix another banned character in ecoretool export

etc/templates/apache2.conf.erb
=> Fixes NYTProf being in production side of config

cf/everything2-production.json
Eliminates a few unneeeded buckets
=> Adds all remaining DNS entries to CF

etc/templates/everything.erb
=> Creates rule for default sitemap mapping

nodepack/restricted_superdoc/new_user_images.xml, nodepack/setting/hrstats.xml
=> Fixes Recent Homenode Images

ecore/Everything/Delegation/htmlpage.pm
=> Remove shockwave call in podcast display

ecore/Everything/Delegation/document.pm
=> Delegates [Nodelet Settings]

nodepack/superdoc/nodelet_settings.xml
=> Removes the code from [Nodelet Settings]

nodepack/htmlcode/rearrangenodelets.xml
=> Deletes rearrangenodelets

ecore/Everything/Application.pm, ecore/Everything/Configuration.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Node/user.pm
Officially support all current nodelets
Fixes #3300
=> Move nodelet groups to E::CONF

nodepack/setting/hrstats.xml, nodepack/user/guest_user.xml
=> Removes nodelet preferences from guest user VARS

cf/everything2-production.json
=> Scaling In confirmed working

ecore/Everything/DataStash/neglecteddrafts.pm, ecore/Everything/Node.pm, ecore/Everything/Node/draft.pm
This is to facilitate the move to react
Fixes #3309
=> Changes the way in which neglecteddrafts get built

cf/everything2-production.json, ops/run-codebuild.rb
Fixes deployment to deploy at current scale
Fixes #3315
=> Changes scaling threshhold to be 80%

cf/everything2-production.json
=> Updates memory requirements to 2g

ecore/Everything/Node/draft.pm
=> Fixes neglecteddrafts structure to dodge issue with show_content

ecore/Everything/Delegation/nodelet.pm, react/components/E2ReactRoot.js, react/components/Nodelets/NeglectedDrafts.js
=> Move Neglected Drafts to React

ecore/Everything/Node/draft.pm, react/components/Nodelets/NeglectedDrafts.js, templates/nodelets/neglected_drafts.mi
Fixes warning and default no neglect behavior
Also fixes a mason interaction
Fixes #3317
=> Removes the author_user parameter in neglecteddrafts

ecore/Everything/Node/draft.pm, react/components/Nodelets/NeglectedDrafts.js
=> Fixes bad namespacing in neglecteddrafts

nodepack/datastash/hrstats.xml, nodepack/setting/hrstats.xml, nodepack/user/everyone.xml
=> Adds the hrstats datastash to the nodepack

ecore/Everything/Delegation/htmlcode.pm
=> Fixes error costing us $1.00/day

ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/htmlcode.pm, templates/helpers/guest_nodeshell_banner.mi, templates/zen.mc
=> Eliminates the guest_user_banner

nodepack/htmlcode/guestuserbanner.xml
=> Deletes [guestuserbanner]

ecore/Everything/Delegation/htmlcode.pm
=> Fixes CGI::param warning

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value warning

ecore/Everything/Delegation/nodelet.pm
=> Fixes uninitialized value warning for Guest User edge case

ecore/Everything/Delegation/opcode.pm
=> Fixes SQL injection problem in ilikeit

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninit value warning clogging up the logs

ecore/Everything/Delegation/htmlpage.pm
=> Kill of shownodelet for guest user

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value warning in writeup hints

ecore/Everything/Delegation/htmlpage.pm
=> Fixes uninitialized value in htmlpage

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninit value warnings in draft updates

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized warning in writeuphints

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninit value warning in writeuphints

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Fixes uninit value in Drafts

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/HTML.pm, ecore/Everything/NodeBase.pm
=> Changes default connection set to 4byte utf8 collation

www/js/legacy.js
=> Fixes messaging with 4-byte utf-8 characters

nodepack/setting/hrstats.xml, nodepack/superdoc/simple_usergroup_editor.xml
=> Fixes a warning with simple usergroup editor

ecore/Everything/Delegation/document.pm
Test reformatting of document.pm with perltidy vscode extension
Fixes #3375
=> Pulls code out of [simple usergroup editor]

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninit value warning

ecore/Everything/Application.pm, ecore/Everything/Controller.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, react/components/E2ReactRoot.js, react/components/LinkNode.js, react/components/Nodelets/NeglectedDrafts.js, react/components/Nodelets/NewLogs.js, react/components/Nodelets/NewWriteups.js, react/components/Nodelets/QuickReference.js, react/components/Nodelets/RandomNodes.js, react/components/Nodelets/RecommendedReading.js, react/components/Nodelets/SignIn.js, react/components/Nodelets/Vitals.js, react/components/Portals/QuickReferencePortal.js
Clean up double nodelet_content encoding
Added url support to LinkNode
Fixes #3329
=> Moved [Quick Reference] to React

ecore/Everything/Application.pm
=> Fixes React Nodelets broken on the actual nodeid

ecore/Everything/Delegation/document.pm
=> Fixes bugs in Simple Usergroup Editor

ecore/Everything/Delegation/document.pm
=> Fixes error in simple usergroup editor

ecore/Everything/Delegation/document.pm
=> Fixes broken editor endorsements

ecore/Everything/Delegation/document.pm
=> Adds ability for editors to work on usergroups

cf/everything2-production.json
=> Increased memory to 3G

ecore/Everything/Node/user.pm
=> Fixes session API endpoint to return coolsleft as a string

nodepack/restricted_superdoc/system__manual_tool_output.xml, nodepack/restricted_superdoc/user_vars_statistics.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/bounty_order.xml, nodepack/setting/hrstats.xml, nodepack/setting/outlaws.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/user/everyone.xml, nodepack/user/virgil.xml, nodepack/user/webster_1913.xml
=> Updated nodepack with new docs for utilities

ecore/Everything/Delegation/document.pm
=> Fixed two issues that caused warnings to generate on code loading

docker/e2app/Dockerfile
=> Update nodejs version

docker/buildspec.yml
=> Update node version in buildspec

ecore/Everything/Delegation/document.pm
=> Delegates [Everything's Biggest Stars]

ecoretool/lib/ecoretool/base.pm
=> Adds Sheriffs to ect

nodepack/_data/nodegroup.xml, nodepack/setting/egg_commands.xml, nodepack/setting/hrstats.xml, nodepack/setting/room_topics.xml, nodepack/usergroup/sheriffs.xml
=> Adds the [Sheriffs] to the nodepack from production

docker/e2app/apache2_wrapper.rb
=> Fixes the UA ban features

ecore/Everything/APIClient.pm
=> Fixes whitespacing
