everything2/everything2

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Minor fixes 20150829

ecore/Everything/Delegation/htmlcode.pm
Creating a pull request to merge these two.
=> Provide a link to deal more conveniently with spammers

ecore/Everything/Delegation/htmlcode.pm
=> Add fetish to badword list

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/opcode.pm
Nothing to do with IP blacklisting, sorry.
=> Improve notification/documentation of bulk removals

vagrant/cookbooks/e2helper/recipes/default.rb
=> Added in xz-util and xdelta3 so that better backups strategies can occur

vagrant/cookbooks/e2web/attributes/default.rb, vagrant/cookbooks/e2web/recipes/default.rb
Default symlinks for ssl, drop certificates based out of attributes
Closes #47
=> Create default module symlinks for ssl

vagrant/cookbooks/e2web/recipes/default.rb
This creates a snakeoil cert for development environments
Fixes #49
=> Snakeoil for dev

vagrant/cookbooks/e2web/recipes/default.rb
=> Remove the bad only_if check for the cert in production

vagrant/Vagrantfile, vagrant/cookbooks/e2web/templates/default/everything.erb
=> Default TLS configuration for Apache

.gitmodules, ecoretool/ecoretool.pl, ecoretool/lib/ecoretool/base.pm, ecoretool/lib/ecoretool/bootstrap.pm, ecoretool/lib/ecoretool/export.pm, ecoretool/lib/ecoretool/help.pm, ecoretool/lib/ecoretool/import.pm, ecoretool/lib/ecoretool/nodeidmove.pm
This eliminates the ecoretool submodule from the repository. The history was destroyed, but that's not a big deal; it still exists in the ecoretool repo.
=> Remove ecoretool as a submodule

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/clearimage.xml
=> As a part of the TLS move, retire the clearimage code

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
A first batch of major library changes for http references
=> Pursuing #57

ecore/Everything/S3.pm, tools/letsencrypt_s3_hook.pl
=> Add in the letsencrypt hook for s3

vagrant/cookbooks/e2tls/recipes/default.rb
=> Add in curl for letsencrypt

tools/letsencrypt_s3_hook.pl
=> Upload the key to the keyexchange bucket when its done

ecore/Everything/S3.pm, tools/fetch_tls_keys.pl
=> Creates a tls key fetch script for production

vagrant/cookbooks/e2tls/templates/default/dehydrated.config.erb
=> Make the default for letsencrypt the production URL

ecore/Everything/Delegation/htmlcode.pm
=> Hard code the homenode image host as https for right now

ecore/Everything/Application.pm
=> Fix base href for majority forms for guest user

ecore/Everything/Delegation/maintenance.pm
=> Pull all of the maintenance code out of the database

tools/generate_sitemap.pl
=> Generate sitemap should push users to https

www/robots.txt
=> Fix the robots.txt for the new https sitemap

vagrant/cookbooks/e2web/templates/default/mod_rewrite.conf.erb
=> It's time for TLS

ecore/Everything/Delegation/htmlcode.pm
=> Put xmltrue in HTTPS namespace

vagrant/cookbooks/e2web/templates/default/ssl.conf.erb
=> Remove RC4 cipher from production

tools/letsencrypt_s3_hook.pl
=> Add the intermediate cert to the letsencrypt_s3_hook.pl script

tools/fetch_tls_keys.pl, tools/letsencrypt_s3_hook.pl
=> Chain support in the key exchange script

ecore/Everything/Delegation/maintenance.pm
crashing mod_perl
We have the most recent version of these maintenances, it just took a bit of precision
Fixes #109
=> Clean up the emergency push bodge to fix symbol table error that was

nodepack/mail/welcome_to_everything2.xml, nodepack/setting/room_topics.xml
=> Registration email is now https

ecore/Everything/Application.pm, ecore/Everything/Delegation/maintenance.pm, tools/javascript_to_s3.pl
=> Completely overhaul the way javascript gets uploaded to the server

ecore/Everything/API.pm, ecore/Everything/API/login.pm, ecore/Everything/API/messages.pm, ecore/Everything/APIRouter.pm, ecore/Everything/HTTP.pm, ecore/Everything/Request.pm, www/api/index.pl
=> Add new router which can handle the proper variation of route endpoints

ecore/Everything/Delegation/htmlcode.pm
=> Move the sortlist to not link to the jscript node

compile/.gitignore, vagrant/cookbooks/e2engine/recipes/default.rb
We won't bother to purge these from the server, but it's good to clean up some of the cruft
Fixes #86
=> Removes the compile directory and the mason module installation.

README.md
=> Small documentation fix for README.md

docs/API.md
=> Initial markdown for the API docs

.gitmodules
=> Fix the git submodules invocation for ntp

docs/API.md
sessions.pm looks for `$data->{passwd}`
=> Make doc match code

docs/API.md
=> Adds utf-8 to the documentation for the APIs

ecore/Everything/API.pm
=> Removes some duplicated code

ecore/Everything/APIRouter.pm, ecore/Everything/Application.pm, ecore/Everything/HTTP.pm, ecore/Everything/Request.pm
=> Only allow family into the APIs for now

docs/API.md, ecore/Everything/API/sessions.pm, ecore/Everything/APIRouter.pm
Both /create and /destroy in sessions gives the output of sessions for the proper user
=> Sessions now properly logs a user out when destroying a session

nodepack/fullpage/in10se's_sandbox_5.xml, nodepack/jscript/message_inbox_javascript.xml, nodepack/superdoc/list_nodes_of_type.xml
=> Get rid of all of the mentions of rawdata, a long dead type

docs/API.md, ecore/Everything/API/sessions.pm, ecore/Everything/Application.pm
=> Adds in leveltitle to the sessions API

vagrant/cookbooks/e2engine/recipes/default.rb
=> Add LWP::UserAgent for the test harness

docs/API.md
=> More notes based on in10se's feedback on API being case sensitive

t/013_sessions_api.t
=> Full test coverage for current state of /api/sessions

docs/API.md, ecore/Everything/API.pm, ecore/Everything/Request.pm, t/013_sessions_api.t
=> Support application/x-www-form-encoded POSTS to aid developers

ecore/Everything/Delegation/htmlcode.pm
=> Fix google ads.

docs/API.md, ecore/Everything/API/sessions.pm, t/013_sessions_api.t
=> Adds special powers to user displays for sessions

ecore/Everything/Delegation/htmlcode.pm
=> Fixes stray server error with obvious syntax problem in draft creation

docs/API.md, ecore/Everything/API/sessions.pm
=> Adds the number of writeups to the users' session display

docs/API.md, ecore/Everything/API/messages.pm, ecore/Everything/API/sessions.pm, ecore/Everything/APIClient.pm, ecore/Everything/Application.pm, t/015_messages_api.t
=> Create the Everything::APIClient and the initial messages API

docs/API.md
=> Fix an important omission in API docs

docs/API.md, ecore/Everything/Application.pm
=> Adds message timestamp to the output, newest messages come out first.

docs/API.md, ecore/Everything/API.pm, ecore/Everything/API/messages.pm, ecore/Everything/APIClient.pm, ecore/Everything/Application.pm
=> Adds in pagination on the messaging API.

ecore/Everything/API/sessions.pm
=> Makes cools actually display properly in sessions

docs/API.md, ecore/Everything/API/messages.pm, ecore/Everything/APIClient.pm, ecore/Everything/Application.pm
=> Messages API can now actually send messages

docs/API.md, ecore/Everything/API.pm, ecore/Everything/API/messages.pm, ecore/Everything/Application.pm
Moose is incredibly impressive here and shows a lot of what it can do with method modifiers to help keep code consistent
Fixes #250
=> Adds archiving and unarchving

docs/API.md, ecore/Everything/API/messageignores.pm, ecore/Everything/API/messages.pm, ecore/Everything/APIClient.pm, ecore/Everything/Application.pm, ecore/Everything/HTTP.pm
=> Adds in the new message ignores API

ecore/Everything/APIClient.pm, ecore/Everything/Application.pm, t/016_messageignores_api.t
=> Add in test coverage for the messageignores API

t/010_insertnode.t
=> Fixes a dumb and really un-useful test for insertnode

nodepack/dbtable/user.xml, nodepack/setting/room_topics.xml
=> We need to remove the users_clan column from the users table

nodepack/dbtable/user.xml
=> Remove the wantsreport column on user

ecore/Everything/Delegation/maintenance.pm, tools/seeds.pl
=> Fix the qareload script

ecore/Everything/DataStash.pm
=> Fixing the globals incantation for DataStash

ecore/Everything.pm, ecore/Everything/APIRouter.pm, ecore/Everything/Globals.pm, ecore/Everything/Node.pm, ecore/Everything/Node/user.pm, ecore/Everything/PluginFactory.pm, t/012_api_routing.t, t/015_messages_api.t, tools/data_generator_heartbeat.pl
=> Massive object model overhaul begins here

docs/API.md, ecore/Everything/Application.pm, ecore/Everything/Node.pm
=> And type to node JSON references

docs/API.md, ecore/Everything/API/e2nodes.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/sessions.pm, ecore/Everything/API/users.pm, ecore/Everything/API/writeups.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Node.pm, ecore/Everything/Node/document.pm, ecore/Everything/Node/e2node.pm, ecore/Everything/Node/nodetype.pm, ecore/Everything/Node/user.pm, ecore/Everything/Node/usergroup.pm, ecore/Everything/Node/writeup.pm, t/013_sessions_api.t
=> Create the first real navigation API: /api/nodes

nodepack/htmlpage/usergroup_display_page.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/clientdev_home.xml, nodepack/usergroup/clientdev.xml, nodepack/usergroup/content_editors.xml, nodepack/usergroup/e2docs.xml, nodepack/usergroup/edev.xml, nodepack/usergroup/gods.xml
=> Removes code execution from usergroup displays

docs/API.md, ecore/Everything/API/usergroups.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Node/e2node.pm, ecore/Everything/Node/helper/group.pm, ecore/Everything/Node/usergroup.pm
=> Initial commit of usergroup apis

ecore/Everything/API/e2nodes.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/writeups.pm, ecore/Everything/Node/e2node.pm, ecore/Everything/Node/writeup.pm
=> Fix the APIs so that json_display is user-aware

docs/API.md, ecore/Everything/Node/writeup.pm
=> Does the right thing for node reputation

docs/API.md, ecore/Everything/API/sessions.pm, ecore/Everything/APIClient.pm, t/013_sessions_api.t
=> Rename the sessions/destroy API endpoint to be sessions/delete

docs/API.md
=> Fix a series of omissions in the user property documentation

docs/API.md, ecore/Everything/Node.pm, ecore/Everything/Node/user.pm
=> Add in createtime and an author reference for each of the nodetypes

docs/API.md
=> Clarified text that was confusing about what versions APIs start at.

docs/API.md, ecore/Everything/Node/e2node.pm, ecore/Everything/Node/helper/group.pm, ecore/Everything/Node/writeup.pm
=> Add in softlinks on writeups and e2nodes

ecore/Everything/NodeBase.pm
=> Raise SQL errors in the development environment

vagrant/cookbooks/e2engine/recipes/default.rb
=> Add Perl::Critic to e2engine

docs/API.md, ecore/Everything/API/nodes.pm, ecore/Everything/API/writeups.pm, ecore/Everything/Node/container.pm
Return 404 otherwise
Fixes #322
=> Check for the right type of node in the node API

docs/API.md, ecore/Everything/Node/writeup.pm, ecore/Everything/Node/writeuptype.pm
=> Writeuptype inside of writeups

ecore/Everything/ect/user.pm
=> Don't ever store message_forward_to

tools/critic.pl, tools/tidy.pl
=> Perltidy and Perlcritic utils

docs/API.md, ecore/Everything/API/nodes.pm, ecore/Everything/API/usergroups.pm, ecore/Everything/APIClient.pm, ecore/Everything/Node.pm, ecore/Everything/Node/helper/group.pm
Also adds node removal as an API
Fixes #338
=> Add in usergroup adding and removing

t/017_usergroups.t
=> Add in the nearly omitted tests

ecore/Everything/Delegation/htmlcode.pm
=> Attempted fix for messages with spaces

t/013_sessions_api.t, t/016_messageignores_api.t, t/017_usergroups.t
=> Look nodes up through the frontend instead of peeking in the database

ecore/Everything/Node/user.pm
=> is_online supprt inside of user

docs/API.md, ecore/Everything/Node/user.pm
=> Add in message_forward_to for the message system

ecore/Everything/Node.pm, ecore/Everything/NodeBase.pm
=> Skip maintenances on updates if the APIs are calling them

ecore/Everything/API.pm, ecore/Everything/API/messageignores.pm, ecore/Everything/API/messages.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/sessions.pm, ecore/Everything/API/tests.pm, ecore/Everything/API/usergroups.pm, ecore/Everything/Application.pm, ecore/Everything/Request.pm, t/014_api_versions.t
This should DRY up the API objects
Fixes #347
=> Refactor who holds onto the API versionining information.

docs/API.md, ecore/Everything/API/e2nodes.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/usergroups.pm, ecore/Everything/API/users.pm, ecore/Everything/APIClient.pm, ecore/Everything/Node.pm, ecore/Everything/Node/document.pm, ecore/Everything/Node/usergroup.pm, t/017_usergroups.t
=> Add in API update ability

nodepack/_data/links.xml, nodepack/mail/everything2_password_reset.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/what's_my_password_.xml
=> Fix E2 password reset link, as it was not https

ecore/Everything/API/systemutilities.pm, ecore/Everything/APIClient.pm, ecore/Everything/HTML.pm, t/018_systemutilities.t
=> Adds an API for flushing rooms

docs/API.md
=> Add the docs for roompurge

ecore/Everything/API/messages.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/sessions.pm, ecore/Everything/API/systemutilities.pm, ecore/Everything/Request.pm
=> Add in the user as a blessed object for future page renders

ecore/Everything/APIRouter.pm
=> Fixes a problem where the React.js environment couldn't connect

ecore/Everything/Delegation/container.pm, ecore/Everything/HTML.pm
=> Fully delegate containers to their own perl module

ecore/Everything/Request.pm
=> Fixes issue where cookie gets overwritten every pageload

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Remove space checking in container code

ecore/Everything/Request.pm
=> Fix ISE on login with no password

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm
=> Pull all of the nodelet code out of the database and into PMs

www/js/1874924.js
=> Add back in replyToCB

nodepack/_data/links.xml, nodepack/htmlpage/classic_user_edit_page.xml, nodepack/jscript/default_javascript.xml, nodepack/jscript/sortlist.xml
=> Fix issues with sortlist. It is still not clear if sortlist works

ecore/Everything/Delegation/htmlcode.pm
=> Fixes crash in nodelets that Brawl was having

ecore/Everything/HTML.pm
=> Removes genContainer from the codebase

ecore/Everything/Delegation/opcode.pm
=> Removes the updateNodelet calls inside of message

nodepack/nodelet/recent_nodes.xml, nodepack/restricted_superdoc/oldminerian_autonomous_poking_machine.xml, nodepack/superdoc/show_user_vars.xml, nodepack/superdocnolinks/n-wing's_plaything.xml, nodepack/superdocnolinks/vars_information.xml, nodepack/user/cool_man_eddie.xml, nodepack/user/edb.xml, nodepack/user/klaproth.xml, nodepack/user/webster_1913.xml
=> Remove all of the displayref code in the nodebase

ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/HTML.pm
Also clean up nodelet display because there's no reason why we should ever need to call updateNodelet
Fixes #465
=> Add in htmlpage delegation

vagrant/cookbooks/e2tls/recipes/default.rb
=> Add in PAWS to the e2tls cookbook

vagrant/cookbooks/e2tls/recipes/default.rb, vagrant/cookbooks/e2tls/templates/default/dehydrated.config.erb
=> Add in a lot of platform support for PAWS and the AWS ACM API

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlpage.pm
=> Support X-Forwarded-Proto

vagrant/cookbooks/e2web/templates/default/mod_rewrite.conf.erb
=> Fix the template to use x-forwarded-proto

www/yandex_44f770ae4d7c2332.html
=> Add in Yandex webmaster token

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Request.pm
=> Record browser no matter how the user gets to the site

nodepack/stylesheet/kernel_blue.xml
=> Fix Kernel Blue problem which gave ReadThis odd margins

ecore/Everything/Delegation/nodelet.pm, nodepack/nodelet/everything_most_wanted.xml
=> Nuke Everything Most Wanted

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm
=> Retires the hasJS htmlcode

tools/aws_acm_cert_upload.pl, tools/stripvar.pl
=> Add the AWS ACM cert upload script to the repository

vagrant/cookbooks/e2tls/recipes/default.rb
=> Let the AWS ACM upload script run once a day

ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/nodelet.pm
=> Put back brawl's nodelet (sorry buddy)

nodepack/nodelet/quick_reference.xml
=> Add quick reference back to nodepack

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds mason back into e2engine

ecore/Everything/API.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTMLRouter.pm, ecore/Everything/Router.pm
=> Keeps warnings from happening when saving a draft

nodepack/superdoc/reputation_graph.xml
=> Fix the reputation graph warning

ecore/Everything.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/systemutilities.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/opcode.pm, ecore/Everything/HTML.pm, ecore/Everything/Request.pm, ecore/Everything/S3.pm
Also do some perlcritic cleanup for obvious bugs
Fixes #458
=> Eliminate updateNodelet calls.

ecore/Everything/Delegation/htmlcode.pm
=> Eliminate old VARS shim for notransitions

ecore/Everything.pm
=> Turn on Mason template compilation in production

ecore/Everything/Application.pm
=> Try the fix one more time, splitting out the double-splat

nodepack/message/_me_shuts_up.xml, nodepack/message/awesome..xml, nodepack/message/doesn't_work_yet..xml, nodepack/message/not_found.xml, nodepack/message/securitize.xml, nodepack/nodetype/message.xml
=> Eliminate the message nodetype

ecore/Everything/Delegation/htmlpage.pm
Other delegates as I am working through the list
Fixes #540
=> Delegate e2node and writeup displays

ecore/Everything/dataprovider/links.pm
=> Fix a dumb typo

ecore/Everything/Delegation/htmlpage.pm
=> Add in more delegated htmlpages so progress continues

ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm
=> Removes the printable code

nodepack/htmlcode/displaywriteuptext.xml, nodepack/htmlcode/printable.xml, nodepack/htmlcode/standard_html_screen.xml, nodepack/htmlpage/e2node_display_page.xml, nodepack/superdoc/25.xml, nodepack/superdoc/everything_new_nodes.xml, nodepack/superdoc/old_writeup_settings.xml
Fixes #557
Fixes #556
Fixes #555
=> Cleans up printability in htmlcodes

nodepack/htmlpage/superdocnolinks_display_page.xml, nodepack/setting/room_topics.xml
=> Fixes inconsistently named display page for superdocnolinks

ecore/Everything/Delegation/htmlpage.pm
=> Another round of delegated htmlpages

nodepack/superdoc/usergroup_discussions.xml
=> Fixes perl warning in usergroup discussions

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/HTML.pm
=> Pull more htmlpages out of the database

ecore/Everything/DataStash.pm, ecore/Everything/DataStash/editing_invalid_authors.pm, ecore/Everything/DataStash/editing_null_node_titles.pm, ecore/Everything/DataStash/editing_writeups_bad_types.pm, ecore/Everything/DataStash/editing_writeups_broken_titles.pm, ecore/Everything/DataStash/editing_writeups_invalid_parents.pm, ecore/Everything/DataStash/editing_writeups_under_20_characters.pm, ecore/Everything/DataStash/editing_writeups_without_formatting.pm, tools/data_generator_heartbeat.pl
=> New data generator jobs to replace [Robotic Editor Shack] nodetest items

ecore/Everything/DataStash/editing_writeups_without_formatting.pm
=> Limits unformatted writeups to 200

nodepack/datastash/editing_invalid_authors.xml, nodepack/datastash/editing_null_node_titles.xml, nodepack/datastash/editing_writeups_bad_types.xml, nodepack/datastash/editing_writeups_broken_titles.xml, nodepack/datastash/editing_writeups_invalid_parents.xml, nodepack/datastash/editing_writeups_under_20_characters.xml, nodepack/datastash/editing_writeups_without_formatting.xml, nodepack/oppressor_superdoc/content_reports.xml, nodepack/setting/room_topics.xml
=> Add in content reports and data stash nodes

ecore/Everything/Delegation/htmlcode.pm, tools/qareload.pl
Also, make sure that qa reload calls the lengthy script
Fixes #603
=> Add the new Content Report tool to the Master Control section of CE's

vagrant/cookbooks/e2cron/recipes/default.rb
=> Adds the cronjob for lengthy datastash nodes

nodepack/superdoc/e2_gift_shop.xml
=> Fix warnings in the E2 gift shop

ecore/Everything/DataStash/editing_null_node_titles.pm
=> Adding support for blank title in null node title check

ecore/Everything/DataStash/editing_writeups_without_formatting.pm
=> Ignores the E1 era for old writeups

ecore/Everything/DataStash/editing_writeups_without_formatting.pm
=> Fixes the writeups without formatting threshold to be 2001

ecore/Everything/DataStash/editing_writeups_linkless.pm
=> Adds the linkless writeup to the content reports

ecore/Everything/Delegation/htmlpage.pm
=> Delegate more htmlpages

ecore/Everything/Delegation/htmlpage.pm
=> Perlcritic clean htmlpage delegation

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/maintenance.pm
Clean up 100 or so perlcritic problems
Push more helper subroutines into Everything::Application
Fixes #580
=> Delegate all of the htmlpages.

ecore/Everything/Delegation/htmlcode.pm
=> Fix Everything Code Lister in the Everything Developer nodelet

ecore/Everything/DataStash/altfrontpagecontent.pm
=> Fixes a voting density problem

nodepack/setting/room_topics.xml, nodepack/superdoc/recent_registry_entries.xml
=> Fixes code duplication in [recent registry entries]

ecore/Everything.pm, ecore/Everything/Controller.pm, ecore/Everything/Controller/node.pm, ecore/Everything/DataStash/altfrontpagecontent.pm, templates/helpers/linknode.mi, templates/helpers/randomnode.mi, templates/nodelets/Base.mc, templates/nodelets/epicenter.mi, templates/zen.mc
Also adds the new linknode method
Fixes #643
=> Allows the $REQUEST object as a global in templates

ecore/Everything/Delegation/htmlcode.pm
=> Fixes bad conditional assignment in show_content

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
=> Fixes gzip calculations to clean up warnings in cdn links

ecore/Everything/Delegation/htmlcode.pm
=> Uninitialized value warnings in show_content

ecore/Everything/Application.pm
=> Cleans up warning in some logic in linkNodeTitle

ecore/Everything/Application.pm
=> Fixes mod_perl unsafety in cleanupHTML

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Request.pm
=> Fixes two warnings with unitialized values

ecore/Everything.pm
=> Fixes warning in Everything.pm

ecore/Everything/Delegation/container.pm
=> Fixes guest user zen warnings

ecore/Everything/Delegation/htmlcode.pm
=> Fixes warning in unfavoritenoders check in zenwriteups

ecore/Everything/Delegation/htmlcode.pm
Fixes #668
Fixes #669
Fixes #670
=> Fixes warnings in the main log and some Perl::Critic issues

ecore/Everything/Delegation/htmlcode.pm
Also warnings cleanup from production
Fixes #672
Fixes #673
Fixes #675
=> Fixes a bug introduced by operator precedence issues

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Fixes two high-occurance warnings

ecore/Everything/Delegation/htmlcode.pm
Fixes #680
Fixes #681
Fixes #682
=> Fixes a number of constant page warnings

ecore/Everything/Delegation/htmlcode.pm
Fixes #688
Fixes #689
Fixes #690
=> Fixes more numerous warnings in the htmlcode delegations

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlpage.pm
Fixes #692
Fixes #693
Fixes #694
=> Clean up more warnings with bad text setups

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm
Fixes #697
Fixes #698
Fixes #699
=> Fixes the currently top three noisiest warnings

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
Fixes #701
Fixes #702
Fixes #703
=> Cleans up a number of noisy warnings in the code

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm
Fixes #705
Fixes #706
Fixes #707
Fixes #708
Fixes #709
=> Cleans up top 5 noisiest warnings

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/nodelet.pm
Fixes #711
Fixes #712
Fixes #713
Fixes #714
Fixes #715
Fixes #717
Fixes #720
Fixes #721
=> Fixes a lot of noisy warnings

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm
Fixes #723
Fixes #724
Fixes #725
Fixes #726
Fixes #727
Fixes #728
Fixes #729
Fixes #730
=> Clean up a lot of development environment warnings

nodepack/superdoc/site_trajectory.xml, nodepack/superdoc/site_trajectory_2.xml
=> Cleans up the Site Trajectory / Site Trajectory 2 warnings

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm
Fixes #747
Fixes #748
Fixes #749
Fixes #750
Fixes #751
Fixes #752
Fixes #753
Fixes #754
=> Cleans up a lot of messy warnings

ecore/Everything/Delegation/htmlcode.pm
Fixes #756
Fixes #757
Fixes #758
=> Cleans up more warnings in the code

ecore/Everything/Delegation/htmlcode.pm
=> Fixes delegated htmlpage code for edev

ecore/Everything/Delegation/htmlcode.pm
=> Use delegations for drafts

nodepack/fullpage/kaizen_ui_preview.xml, nodepack/setting/room_topics.xml
Cleans now-duplicated code out of the other users xml ticker
Fixes #774
=> Creates new UI preview node

ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Page/kaizen_ui_preview.pm, templates/kaizen.mc
=> Eliminate the mailhead color VARS from the mail display page

ecore/Everything/Delegation/nodelet.pm
Cleans up critic warnings in notelet.pm
Fixes a personal links error
Fixes #428
=> Removes references to legacy notelet vars

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/showchoicefunc.xml
Clean up various warnings and critic items
Fixes #779
=> Remove showchoicefunc

nodepack/superdoc/your_ignore_list.xml
=> Fixes a problem with [Your ignore list]

ecore/Everything/Delegation/htmlpage.pm
=> Fix drafts for review

docs/API.md, ecore/Everything/API/sessions.pm
=> Adds infravision to sessions API and docs

ecore/Everything/Delegation/htmlpage.pm
=> Fix the mail node display reference problem

ecore/Everything/Delegation/htmlcode.pm
This doesn't break anything and is in line with the last database version, which worked, but the datastash is empty in my development environment, so it hasn't been tested on real data.
=> HTML encode content of nodes in xml output

ecore/Everything/API/messageignores.pm, ecore/Everything/Application.pm, ecore/Everything/HTML.pm, ecore/Everything/Node/user.pm
=> Refactors the message ignore code to the now much more robust user model

ecore/Everything.pm, ecore/Everything/API/messages.pm, ecore/Everything/API/sessions.pm, ecore/Everything/APIRouter.pm, ecore/Everything/HTML.pm, ecore/Everything/Node/user.pm, ecore/Everything/Request.pm
=> Ports REQUEST->USER to REQUEST->user for the new models

ecore/Everything/Delegation/htmlpage.pm, ecore/Everything/Delegation/maintenance.pm
=> Fixes hamster error in deleting drafts

ecore/Everything/Controller.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, ecore/Everything/HTML.pm, ecore/Everything/Node/user.pm
Fixes #804
Fixes #805
Fixes #806
Fixes #808
Fixes #809
Fixes #810
=> Fixes a small pile of noisy warnings

ecore/Everything/Controller.pm, ecore/Everything/Delegation/opcode.pm, ecore/Everything/HTML.pm, ecore/Everything/Node.pm, ecore/Everything/Node/writeup.pm, templates/helpers/linknode.mi, templates/helpers/openform.mi, templates/nodelets/new_writeups.mi, tools/masontest.pl
=> Adds in templatized code for new_writeups

docs/API.md, ecore/Everything/Node/writeup.pm
=> Adds the e2node parent to the writeups API

t/020_writeups.t
=> Add in writeup tests to pave the way for a New Writeups revamp

ecore/Everything/Delegation/htmlcode.pm
No idea how it broke
Fixes #823
=> Fixes the delete nodeshell button for admins inside of e2nodetools

ecore/Everything/DataStash/editing_e2nodes_with_duplicate_titles.pm
=> Add new data generator job for duplicate titles

nodepack/datastash/editing_e2nodes_with_duplicate_titles.xml, nodepack/oppressor_superdoc/content_reports.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/ticker/new_writeups_atom_feed.xml
=> Various fixes from admins and the new duplicate titles report

t/020_writeups.t
=> Fixes missed test cases with regards to guest user

nodepack/setting/egg_commands.xml, nodepack/superdoc/magical_writeup_reparenter.xml
=> Fixes the magical writeup reparenter

tools/qareload.pl
=> Fixes the qareload script to create a utf8 database

docs/API.md
=> Add in docs for newwriteups API

vagrant/Vagrantfile
=> Adding a friendly name to vagrant up

ecore/Everything.pm
=> Cleans up perl critic warnings in Everything.pm

ecore/Everything/DataStash.pm
=> Fixes a minor perlcritic warning in DataStash.pm

ecore/Everything/Application.pm, ecore/Everything/S3.pm, tools/letsencrypt_s3_hook.pl
=> Invasive perlcritic fixes for Everything::S3

ecore/Everything/Application.pm
Lots of small changes, but in particular we should be worried about diffs and HTML screening
Fixes #867
=> Fix Everything::Application for perlcritic warnings

ecore/Everything/API.pm
=> Fix perlcritic warnings in Everything::API

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adding Try::Tiny to the explicit module list

ecore/Everything.pm, ecore/Everything/NodeCache.pm
=> Everything::NodeCache now passes perlcritic with one silence

ecore/Everything/API/messageignores.pm, ecore/Everything/API/messages.pm, ecore/Everything/API/nodes.pm, ecore/Everything/API/sessions.pm, ecore/Everything/Node.pm
I'll tag and come back to them (maybe) later.
Fixes #875
=> Silences some perlcritic warnings that aren't safe to fix.

ecore/Everything/APIRouter.pm
=> Fixes perlcritic warning in APIRouter for grep usage

ecore/Everything/HTML.pm
=> Fix up problems with perlcritic and Everything::HTML

ecore/Everything/Configuration.pm
=> Fix quick open warning for perlcritic

ecore/Everything/NodeBase.pm
=> Cleans up many perlcritic warnings in Everything::NodeBase

nodepack/restricted_superdoc/the_old_hooked_pole.xml, nodepack/setting/egg_commands.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/e2_gift_shop.xml, nodepack/superdoc/iron_noder_progress.xml, nodepack/superdoc/message_inbox.xml, nodepack/superdoc/the_everything2_voting_experience_system.xml
=> Add in updated nodepack entries for 2017

ecore/Everything/PluginFactory.pm
Cleans up one and silences one Perl::Critic issue
Fixes #895
=> Properly catch two different flavors of eval in PluginFactory

ecore/Everything/Delegation/container.pm
=> Fixes to legit bugs as found by Perl::Critic

ecore/Everything/Delegation/opcode.pm
=> Fixes a ton of small bugs and perlcritic stuff in opcodes

ecore/Everything/Delegation/maintenance.pm
=> Fixes a bunch of Perl::Critic stuff in maintenances

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/cooluncoolit.xml
=> Removes CoolUncoolIt; it wasn't used

ecore/Everything/dataprovider/base.pm, ecore/Everything/dataprovider/nodegroup.pm, ecore/Everything/dataprovider/nodeparam.pm
=> Answer the perlcritic demon for the dataprovider nodes

ecore/Everything/FormMenu.pm
The only reason why these weren't worse is that they were on really unpopular superdocs
Fixes #910
=> Fixed a bunch of memory leaks in FormMenu and now critic clean

ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlpage.pm
=> Starts the code-out-of-the-database process for superdocs et al

nodepack/setting/room_topics.xml, nodepack/stylesheet/simplicity.xml, nodepack/superdoc/25.xml
Other nodepack updates in as well.
Fixes #921
=> Removes code from 25 from the database

nodepack/superdoc/a_year_ago_today.xml
=> Removes code from [A Year Ago Today] in the database

ecore/Everything/Delegation/document.pm
=> Delegates [About Nobody]

nodepack/superdoc/about_nobody.xml
=> Removes [About Nobody] from the database code

ecore/Everything/Delegation/document.pm
=> Delegates [Admin Settings]

ecore/Everything/Delegation/document.pm
=> Delegate [Advanced Settings]

ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlpage.pm
=> Delegate [Ask Everything: Do I have the Swine Flu?]

ecore/Everything/Delegation/document.pm
=> Delegates [Available Rooms]

nodepack/superdoc/available_rooms.xml
=> Remove code from [Available Rooms]

ecore/Everything/Delegation/htmlcode.pm
=> Fixes uninitialized value warnings in the logs

nodepack/superdoc/everything's_most_wanted.xml
=> Removes dead img link and fixes typo in [Everything's Most Wanted]

ecore/Everything/Delegation/document.pm
=> Delegates [bad spellings listing]

nodepack/superdoc/bad_spellings_listing.xml
=> Remove the code from [bad spellings listing]

ecore/Everything/Delegation/document.pm
=> Delegates [bestow easter eggs]

ecore/Everything/Delegation/document.pm
=> Delegate [between the cracks]

ecore/Everything/Delegation/document.pm
=> Pull [Blind Voting Booth] into a delegation module

ecore/Everything/Delegation/document.pm
=> Delegates [Buffalo Generator]

ecore/Everything/Delegation/document.pm
=> Delegates [Buffalo Haiku Generator]

nodepack/superdoc/buffalo_haiku_generator.xml
=> Removes the code from Buffalo Haiku Generator

ecore/Everything/Delegation/document.pm
=> Delegate [chatterlighter]

ecore/Everything/Delegation/document.pm
=> Delegates [Clientdev home]

nodepack/superdoc/clientdev_home.xml
=> Remove code from [clientdev home]

ecore/Everything/Delegation/document.pm
=> Delegates [confirm password]

ecore/Everything/Delegation/document.pm
=> Delegates [Cool Archive]

nodepack/_data/links.xml, nodepack/restricted_superdoc/node_heaven_title_search.xml, nodepack/restricted_superdoc/oldminerian_ban_tester.xml, nodepack/superdoc/create_a_new_user.xml, nodepack/superdoc/create_a_node.xml, nodepack/superdoc/drafts_for_review.xml, nodepack/superdoc/my_big_writeup_list.xml
=> Cleans up [Create a new user] and retires it

ecore/Everything/Delegation/document.pm
=> Delegates [create a node]

nodepack/superdoc/create_a_node.xml
=> Remove code from [create a node]

ecore/Everything/Delegation/document.pm, nodepack/superdoc/create_a_node.xml
=> Retires [create a node]

ecore/Everything/Delegation/document.pm
=> Delegates [Create a Registry]

nodepack/_data/links.xml, nodepack/_data/nodeparam.xml, nodepack/superdoc/create_a_registry.xml
=> Remove the code from [create a registry]

ecore/Everything/Delegation/document.pm
=> Delegates [Create Category]

ecore/Everything/Delegation/document.pm
=> Delegates [Create Room]

nodepack/superdoc/create_room.xml
=> Removes code from [Create Room]

ecore/Everything/Delegation/document.pm
=> Delegates [Database Lag-o-Meter]

nodepack/superdoc/database_lag-o-meter.xml
=> Pull the code from [Database Lag-o-meter]

ecore/Everything/Delegation/document.pm
=> Delegates [Decloaker]

nodepack/superdoc/decloaker.xml
=> Removes the code from [Decloaker]

nodepack/superdoc/delete_category.xml
=> Removes [Delete Category]

ecore/Everything/Delegation/document.pm
=> Delegate [Disable Actions]

nodepack/superdoc/disable_actions.xml
=> Remove code from [Disable Actions]

ecore/Everything/Delegation/document.pm
=> Delegate [Display Categories]

ecore/Everything/Delegation/document.pm
=> Delegates [Do you C! what I C!]

ecore/Everything/Delegation/document.pm
=> Delegates [Drafts]

ecore/Everything/Delegation/document.pm
=> Delegates [Drafts for Review]

nodepack/superdoc/drafts_for_review.xml
=> Removes the code from [Drafts for Review]

ecore/Everything/Delegation/document.pm
=> Delegates [Duplicates Found:]

nodepack/superdoc/duplicates_found_.xml, nodepack/superdoc/jaybonci's_sandbox.xml
Also adds in a quick utility to my sandbox
Fixes #1080
=> Remove the code from [Duplicates Found:]

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Acceptable Use Policy]

nodepack/restricted_superdoc/everything's_richest_noders.xml, nodepack/restricted_superdoc/gp_optouts.xml, nodepack/restricted_superdoc/most_starred_noders.xml, nodepack/restricted_superdoc/users_with_infravision.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/e2_acceptable_use_policy.xml
=> Remove the code from [E2 Acceptable Use Policy]

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Bouncer]

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Collaboration Nodes]

ecore/Everything/Delegation/document.pm
=> Delegate [E2 Full Text Search]

nodepack/superdoc/e2_full_text_search.xml
=> Remove the code from [E2 Full Text Search]

nodepack/htmlcode/giftshop_ching.xml, nodepack/htmlcode/giftshop_eggs.xml, nodepack/htmlcode/giftshop_sanctity.xml, nodepack/htmlcode/giftshop_star.xml, nodepack/htmlcode/giftshop_topic.xml, nodepack/htmlcode/giftshop_votes.xml
=> Adds the new htmlcodes to the nodepack

nodepack/htmlcode/giftshop_sanctify.xml
=> Fixed badly-named htmlcode

nodepack/htmlcode/giftshop_buyvotes.xml
=> Adds giftshop_buyvotes

vagrant/cookbooks/e2tls/recipes/default.rb
=> Comment out ACM cert upload

ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlcode.pm
=> Delegates [E2 Gift Shop]. Fills in the [giftshop_*] htmlcodes

ecore/Everything/Delegation/htmlcode.pm
=> Fixes warnings for uninitialized values in arguments passed to htmlcodes

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Marble Shop]

nodepack/superdoc/e2_marble_shop.xml
=> Removes the code from [E2 Marble Shop]

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Penny Jar]

nodepack/superdoc/e2_penny_jar.xml
=> Remove code from [E2 Penny Jar]

ecore/Everything/Delegation/document.pm
=> Delegates the [E2 Rot13 Encoder]

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Source Code Formatter]

nodepack/superdoc/everything_logs_(log_archive_kind_of_does_this_now).xml
=> Retires an unused superdoc

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Sperm Counter]

nodepack/superdoc/e2_sperm_counter.xml, nodepack/superdoc/jaybonci's_sandbox.xml
Adds a quick debugging statement to [jaybonci's sandbox]
Fixes #1165
=> Removes code from [E2 Sperm Counter]

nodepack/superdoc/snowisms_generator.xml
=> Retires the blank document snowisms generator

ecore/Everything/Delegation/document.pm
=> Delegate [E2 Ticket Center]

ecore/Everything/Delegation/document.pm
=> Delegates [E2N]

nodepack/superdoc/e2n.xml
=> Remove code from [E2N]

nodepack/superdoc/edev_faq.xml
=> Overhaul [Edev FAQ] to describe modern GitHub practices

ecoretool/lib/ecoretool/base.pm
=> Add the ability to export SIGTITLE to ecoretool

nodepack/_data/nodegroup.xml, nodepack/_data/nodeparam.xml, nodepack/superdoc/e2_staff.xml, nodepack/usergroup/sigtitle.xml
Includes fixes to the [E2 Staff] document due to no longer needing to describe "social" gods.
Fixes #1185
=> Adds in sigtitle.

ecore/Everything/Delegation/document.pm
=> Delegates [E2 Staff]

ecore/Everything/Delegation/document.pm
=> Fixes a small bug in Edev FAQ that disabled forms from working.

nodepack/superdoc/ekn.xml
=> Removes the code from [EKN]

ecore/Everything/Delegation/document.pm
=> Delegate [ENN]

ecore/Everything/Delegation/document.pm
=> Delegates [Edev Documentation Index]

nodepack/superdoc/edev_documentation_index.xml
=> Removes the code from [Edev documentation index]

ecore/Everything/Delegation/document.pm
=> Delegates [Edit Weblog Menu]

nodepack/superdoc/edit_weblog_menu.xml
=> Removes the code from [Edit Weblog Menu]

ecore/Everything/Delegation/document.pm
=> Delegates [Editor Endorsements]

ecore/Everything/Delegation/document.pm
=> Fixes the problem of duplicates in [Editor Endorsements]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Data Pages]

nodepack/superdoc/everything_data_pages.xml
=> Removes the code from [Everything Data Pages]

ecore/Everything/Delegation/document.pm
=> Delegates: [Everything Finger]

nodepack/superdoc/everything_finger.xml
=> Remove code from [Everything Finger]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Document Directory]

nodepack/stylesheet/bookwormier.xml
=> Fixes problem with chatterbox settings in Bookwormier

ecore/Everything/Delegation/document.pm
=> Delegate [Everything I Ching]

ecore/Everything/Delegation/document.pm
=> Delegate [Everything New Nodes]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Poll Archive]

nodepack/superdoc/everything_poll_archive.xml
=> Removes code from [Everything Poll Archive]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Poll Creator]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Poll Directory]

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
=> Adds supplemental javascript as a node param

nodepack/jscript/everything_quote_server_javascript.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml
=> Creates a new javascript node for the Everything Quote Server

ecore/Everything/NodeBase.pm
=> Removes the legacy maintenance codepath which is not in use anymore

www/js/1874924.js, www/js/2157677.js
=> Creates the Everything Quote Server javascript fillings

ecore/Everything/Delegation/document.pm
=> Delegates [Everything Quote Server]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything User Poll]

nodepack/superdoc/everything_user_poll.xml
=> Removes code from [Everything User Poll]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything User Search]

ecore/Everything/Delegation/document.pm, ecore/Everything/NodeBase.pm
Delegates [Everything's Best Users]
Adds development support for diagnosing query issues
Fixes #1294
=> Fix a bug in [A Year Ago Today]

ecore/Everything/Delegation/document.pm
=> Delegates [Everything's Best Writeups]

nodepack/superdoc/everything's_best_writeups.xml
=> Remove code from [Everything's Best Writeups]

ecore/Everything/DataStash/randomnodes.pm
=> Fixes problem with newer perl and a datastash component

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds ruby to e2engine

vagrant/cookbooks/e2engine/attributes/default.rb
=> Adds s3repo to the default attributes for the cookbook

ecore/Everything/Configuration.pm, ecore/Everything/S3.pm
=> Add in default bucket upload for newer S3 module

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds support to the cookbook for ruby-bundler and ruby-dev

tools/aws_registration.rb
=> Adds the aws_registration script to the tools directory

tools/aws_registration.rb
=> Remove timeout that doesn't work on bionic

tools/aws_registration.rb
=> Fix typo in aws_registration.rb

tools/db.rb, vagrant/cookbooks/README.md, vagrant/cookbooks/e2engine/recipes/default.rb, vagrant/cookbooks/e2web/recipes/default.rb
=> Update files from bionic launch

vagrant/cookbooks/e2engine/recipes/default.rb, vagrant/cookbooks/e2tls/default.rb, vagrant/cookbooks/e2tls/recipes/default.rb, vagrant/cookbooks/e2web/recipes/default.rb
=> Remove non-ubuntu branches from the cookbooks

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/S3.pm
=> Backed out compatibility layer for S3 during ubuntu transition

tools/generate-self-signed-cert.rb
=> Add the self-signed-cert generator

vagrant/cookbooks/e2web/metadata.rb, vagrant/cookbooks/e2web/recipes/default.rb, vagrant/cookbooks/e2web/templates/default/everything.erb
=> Always generate self-signed-certs

vagrant/cookbooks/e2engine/recipes/default.rb
This is a pretty big hack, but it'll work for now
Fixes #1354
=> Fixes a signalling issue where the bastion doesn't have apache2

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds a debugging statement for opsworks

ecore/Everything/Configuration.pm
=> Adds the Everything::Configuration section for iam_app_role

vagrant/cookbooks/e2engine/attributes/default.rb, vagrant/cookbooks/e2engine/recipes/default.rb
Remove certificate_manager stanza in defaults
Fixes #1371
=> Fix the explicit key mapping in e2engine

ecore/Everything/S3.pm
=> Adds IAM role support to Everything::S3

tools/aws_registration.rb
=> Use private addresses in the instance registration space

tools/db.rb
=> Fixes the db tool for dev environment

ecore/Everything/Application.pm, ecore/Everything/Controller.pm, ecore/Everything/Controller/fullpage.pm, ecore/Everything/Controller/page.pm, ecore/Everything/Controller/superdoc.pm, ecore/Everything/HTMLRouter.pm, ecore/Everything/HTTP.pm, ecore/Everything/Page.pm, ecore/Everything/Page/node_tracker2.pm, ecore/Everything/Page/other_users_xml_ticker.pm, ecore/Everything/Router.pm, templates/pages/node_tracker.mc, templates/zen.mc
=> Add in support for superdoc page routing at the low level

ecore/Everything/Delegation/htmlcode.pm
=> Convert [uploaduserimage] to mainline Everything::S3 library

ecore/Everything/Link.pm, ecore/Everything/Node.pm, templates/helpers/ed_cooled.mi, templates/zen.mc
=> Support in the model and in the templates for ed cooling

ecore/Everything/Application.pm, ecore/Everything/Page/unimplemented_25.pm
=> Add in disabled and override parameters

ecore/Everything/Delegation/htmlcode.pm
=> Initialize a hash value before we regex it

ecore/Everything/HTML.pm
=> Squelch a few CGI.pm security warnings

ecore/Everything/Delegation/document.pm, ecore/Everything/Delegation/htmlpage.pm
=> Fix the CGI problems inside of hard code

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm
=> Moves disabledactions over to app checks

nodepack/restricted_superdoc/create_node.xml
=> Fixes a few CGI incompatibilities with [Create Node]

nodepack/superdoc/fled_noder_quest_submission.xml, nodepack/superdocnolinks/n-wing's_plaything.xml
=> Fixes CGI.pm compatibility issues that lead to broken pages

ecore/Everything/Delegation/document.pm, ecore/Everything/Page.pm, ecore/Everything/Page/chatterbox_help_topics.pm, templates/pages/chatterbox_help_topics.mc
=> Moves over [Chatterbox help topics] to the page system

vagrant/cookbooks/e2engine/recipes/default.rb
=> Installs Mason's HTMLFilters

ecore/Everything.pm, templates/helpers/category.mi, templates/helpers/linknode.mi, templates/helpers/searchform.mi
=> Install the HTMLEntities plugin and escape correct titles

nodepack/superdoc/list_html_tags.xml
=> Fix an error in list_html_tags

ecore/Everything/ect/node.pm
=> Ecoretool now exports keys in order

ecore/Everything/Page/list_html_tags.pm, templates/pages/list_html_tags.mc
=> Templatizes [List HTML Tags]

nodepack/superdoc/list_html_tags.xml
=> Removes the code from [List HTML Tags]

ecore/Everything/Configuration.pm
=> Add in recaptcha tokens to Everything::CONF

nodepack/superdoc/sign_up.xml
The goal is to let the spam scores bake for a few days
Fixes #1447
=> Adds recaptcha v3 support to the [sign up] page

nodepack/setting/known_spam_domains.xml, nodepack/superdoc/sign_up.xml
=> Adds spam filtering by domain to [Sign Up]

ecore/Everything.pm, ecore/Everything/Page/fezisms_generator.pm, ecore/Mason/Plugin/Everything.pm, ecore/Mason/Plugin/Everything/Filters.pm, templates/helpers/category.mi, templates/pages/fezisms_generator.mc
=> Delegates [Fezisms Generator]. Adds link parsing

nodepack/_data/nodegroup.xml, nodepack/usergroup/news.xml
=> Adds the new News nodegroup to the nodepack

nodepack/superdoc/node_tracker.xml
This was brought on by the newer version of perl
Fixes #1465
=> Fixed a warning with [node tracker]

nodepack/_data/nodeparam.xml, nodepack/setting/webloggables.xml, nodepack/usergroup/news.xml
=> Add in News weblog stuff and remove frontpage

ecore/Everything/DataStash/frontpagenews.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, ecore/Everything/Delegation/opcode.pm, tools/seeds.pl
Eliminates a pile of special cases
Fixes #1468
=> New frontpage code which restricts weblogging to usergroups only

nodepack/_data/nodeparam.xml, nodepack/superdoc/news_for_noders._stuff_that_matters..xml
=> Fix the [News For Noders. Stuff that Matters.] legacy news doc

ecore/Everything/DataStash/frontpagenews.pm
=> Removes the legacy pieces from the data generator for the frontpage

ecore/Everything/Delegation/htmlpage.pm
=> Fixes an editing oversight for notifications

nodepack/notification/frontpage.xml
=> Fixes the frontpage notification

ecore/Everything/Node.pm, ecore/Everything/Node/user.pm, templates/helpers/category.mi, templates/helpers/weblog.mi, templates/zen.mc
Untested, but looks good. There's an existing Javascript problem, but it is at least a starting point
Fixes #1429
=> Adds templatized support for Weblog / Pages

nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/node_backup.xml
=> Fixes Node Backup by specifying the s3host endpoint

ecore/Everything/Delegation/document.pm, ecore/Everything/Page/about_nobody.pm, ecore/Mason/Plugin/Everything/Filters.pm, templates/pages/25.mc, templates/pages/Base.mc, templates/pages/about_nobody.mc, templates/pages/chatterbox_help_topics.mc, templates/pages/fezisms_generator.mc, templates/pages/list_html_tags.mc, templates/pages/node_tracker.mc
Migrates [About Nobody]
Fixes #1481
=> Creates a better Page superclass with which to do things

ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/NodeBase.pm, t/010_insertnode.t, tools/seeds.pl
=> Fixes a magic variable warning in Perl::Critic

ecore/Everything/Controller.pm, ecore/Everything/Controller/page.pm, ecore/Everything/Node/user.pm
=> Cleans up three warnings that were preventing app health from passing

ecore/Everything/Controller/superdoc.pm
=> Fixes an operator issue in superdoc.pm that blocks app health check

ecore/Everything/Node/user.pm
=> Handle empty strings as invalid input in the user model

ecore/Everything/API.pm
=> Squashes an error in routechooser that was causing tests to fail

vagrant/cookbooks/e2web/templates/default/everything.erb
=> Increases the thread size of Apache2 to 800M

ecore/Everything/HTML.pm, ecore/Everything/Node/user.pm, templates/helpers/weblog.mi
Also makes the add-to-usergroup dialogue work
Fixes #1485
=> Fixes logout on templatized pages

ecore/Everything/Delegation/opcode.pm
where it would add weblog template code
Fixes #1509
=> The weblogify opcode has a legacy beavior

nodepack/user/webster_1913.xml, nodepack/usergroup/news.xml
=> Fixes the News doctext

nodepack/superdoc/login.xml
=> Removes old login text from the login node

ecore/Everything/Configuration.pm
=> Adds support for login_location in Everything::Configuration

vagrant/cookbooks/e2engine/attributes/default.rb
=> Adds login location as a configuration item

ecore/Everything/Application.pm, ecore/Everything/Controller/page.pm, ecore/Everything/Controller/superdoc.pm, ecore/Everything/Node/user.pm, ecore/Everything/Page.pm, ecore/Everything/Page/golden_trinkets.pm, ecore/Everything/Page/node_tracker2.pm, ecore/Everything/Page/other_users_xml_ticker.pm, ecore/Everything/PermissionResult.pm, ecore/Everything/PermissionResult/OK.pm, ecore/Everything/PermissionResult/RedirectLogin.pm, ecore/Everything/Security.pm, ecore/Everything/Security/NoGuest.pm, ecore/Everything/Security/Permissive.pm, templates/pages/golden_trinkets.mc
based on user permissions and other potential characteristics.
This is to support pages that are not accessible by Guest User and eventually the restricted superdocs types
Also templatizes [Golden Trinkets]
Fixes #1514
=> Creates a structure for automatic page routing

nodepack/setting/room_topics.xml, nodepack/superdoc/golden_trinkets.xml
=> Remove the code from [Golden Trinkets]

nodepack/superdoc/sign_up.xml
=> Recaptcha now works in development

nodepack/superdoc/sign_up.xml
=> Fixes perl warning in [Sign Up]

ecore/Everything/Application.pm
=> Adds [sign up] name taken code to APP for ease of use

nodepack/superdoc/sign_up.xml
=> Reduces code complexity in [Sign Up]

ecore/Everything/Configuration.pm
=> Adds support for blacklist_interval into Everything::Configuration

vagrant/cookbooks/e2engine/attributes/default.rb
=> Adds the the blacklist interval inside of cookbooks

ecore/Everything/Application.pm
=> Pulls functions out of [Sign Up] for ease of porting

nodepack/superdoc/sign_up.xml
=> Consolidates [Sign up]

ecore/Everything/Application.pm, ecore/Everything/Page/sign_up.pm, ecore/Mason/Plugin/Everything/Filters.pm, templates/pages/sign_up.mc
=> Templatized [Sign Up]

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Page/sign_up.pm, templates/helpers/openform.mi, templates/pages/sign_up.mc
=> Posts recaptcha values to user VARS, display them for editors

ecore/Everything/Delegation/document.pm, ecore/Everything/Page/e2n.pm, ecore/Everything/Page/ekn.pm, ecore/Everything/Page/enn.pm, ecore/Everything/Page/everything_new_nodes.pm, templates/helpers/ennchoice.mi
=> Templatize the numeric nodes

ecore/Everything/Delegation/htmlcode.pm, nodepack/htmlcode/ennchoice.xml, nodepack/htmlcode/newnodes.xml
=> Retires [ennchoice] and [newnodes] (htmlcodes)

ecore/Everything/Delegation/document.pm, ecore/Everything/Page/e2_full_text_search.pm, templates/pages/e2_full_text_search.mc
=> Templatizes [E2 Full Text Search]

nodepack/jscript/default_javascript.xml, nodepack/superdoc/everything2_elsewhere.xml
=> Pull code from everything2 elsewhere

templates/pages/everything2_elsewhere.mc
=> Hides messages section from [Everything2 Elsewhere]

ecore/Everything/Application.pm
=> Fixes problem with dead nodes

ecore/Everything/Node.pm, ecore/Everything/Node/null.pm, ecore/Everything/Node/writeup.pm, templates/helpers/linknode.mi, templates/nodelets/new_writeups.mi
=> Fix common busted node problems for now

templates/helpers/linknode.mi
=> Put an undefined check into linknode

docs/API.md
=> Fix trailing sentence in API documentation

vagrant/cookbooks/e2engine/libraries/helper.rb, vagrant/cookbooks/e2engine/recipes/default.rb
Also properly restarts on everything.conf.json rewrite
Fixes #1578
Fixes #1373
=> Clears the Mason2 cache on deploy

ecore/Everything/Page/sign_up.pm
=> Enforce recaptcha

ecore/Everything/Page/sign_up.pm, templates/pages/sign_up.mc
=> Remove 'evil robot spammer' checkbox

ecore/Everything/Controller.pm, ecore/Everything/Page/is_it_april_fools_day_yet.pm, templates/helpers/is_special_date.mi, templates/pages/is_it_holiday.mc
=> Adds support for the "Is it April Fools' Day Yet?" page and its like

nodepack/restricted_superdoc/node_notes_by_editor.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/egg_commands.xml, nodepack/setting/known_spam_domains.xml, nodepack/setting/outlaws.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/superdoc/iron_noder_progress.xml, nodepack/superdoc/is_it_april_fools'_day_yet_.xml, nodepack/user/everyone.xml, nodepack/user/webster_1913.xml
=> Nodepack update. Removes code from April Fool's doc

vagrant/cookbooks/e2engine/libraries/helper.rb
=> Add in the helper debugging for is_webhead

www/ads.txt
=> Adding ads.txt

nodepack/setting/egg_commands.xml, nodepack/setting/room_topics.xml, nodepack/stylesheet/in10se_bootstrap.xml, nodepack/superdoc/message_inbox_2.xml, nodepack/superdoc/text_formatter.xml, nodepack/user/everyone.xml, nodepack/user/klaproth.xml, nodepack/user/virgil.xml, nodepack/user/webster_1913.xml
=> Nodepack update and fixes to various jscss hardcodings

ecore/Everything/Application.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Node/helper/s3.pm, www/js/1874924.js
=> Removes references to the old jscss bucket

nodepack/jscript/autoformat_javascript.xml, nodepack/jscript/colorclass.js.xml, nodepack/jscript/default_javascript.xml, nodepack/jscript/everything_quote_server_javascript.xml, nodepack/jscript/htmltoolbar.xml, nodepack/jscript/jstest.xml, nodepack/jscript/message_inbox_javascript.xml
=> Fixes the nodepack for various js items that were bumped

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes jscss host attribute

serverless/Makefile
=> Updates the serverless Makefile to point to the new tools directory

serverless/buildspec.yml
=> Adds new buildspec paths for codebuild

tools/createdeps.pl
=> Adds configurable directory support for createdeps tool

vagrant/cookbooks/e2engine/recipes/default.rb
=> Adds in the createdeps script to the recipes

serverless/deplists/app.json
=> Adds in dependencies for Paws

vagrant/cookbooks/e2web/templates/default/everything.erb
=> Adds in the new libraries path into PerlSwitches

serverless/deplists/app.json
=> Adds Config::INI to the module deplist

serverless/deplists/app.json
=> Adds Mixin::Linewise and its deps to the pile

serverless/deplists/app.json
=> Paws requries URI Template

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the default for smtp_user

tools/cleanCbox.pl, tools/data_generator_heartbeat.pl, tools/database_backup_to_s3.pl, tools/e2_staging_dump.pl, tools/expirerooms.pl, tools/genRDF.pl, tools/genStats.pl, tools/generate_sitemap.pl, tools/javascript_to_s3.pl, tools/newstats.pl, tools/nodeletstats.pl, tools/qareload.pl, tools/reaper.pl, tools/refreshRoom.pl, tools/seeds.pl, tools/stripvar.pl, tools/user_vars_stats.pl, tools/writeupdump.pl
=> Fixes paths for various utilities

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the default for smtp_pass from the cookbooks

ecore/Everything/Configuration.pm, t/011_configuration.t, t/testdata/config_2.json, t/testdata/config_3.json, vagrant/cookbooks/e2engine/attributes/default.rb
=> Remove notification email from the configuration parser

nodepack/mail/backup_ready_mail.xml
=> Removes [backup ready mail]

vagrant/cookbooks/e2engine/recipes/default.rb
=> Runs get_secrets in production

ecore/Everything/Configuration.pm
=> Reads everypass from disk

ecore/Everything/Configuration.pm
=> Fixes password reading from disk problem

vagrant/cookbooks/e2engine/recipes/default.rb
=> Seeds the recaptcha secret

ecore/Everything/Configuration.pm
=> Adds in support for the recaptcha secret from disk

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes recpatcha secret default

vagrant/cookbooks/e2engine/recipes/default.rb
=> Subscribes to the infected ips secret

ecore/Everything/Configuration.pm
=> Supports JSON in on-disk secrets

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the default of infected IPs on the attributes block

vagrant/cookbooks/e2web/recipes/default.rb, vagrant/cookbooks/e2web/templates/default/everything.erb
Grabs secrets for blocking from disk
Fixes: #1676
=> Changes to cookbooks for apache config

vagrant/cookbooks/e2engine/recipes/default.rb
=> Fixes vagrant and chef bootstrapping issues

vagrant/cookbooks/e2engine/recipes/default.rb
=> Skinnies down aws sdk usage

tools/aws_registration.rb
=> Fixes aws registration issue where it is using the entire sdk

tools/log_deliver_to_s3.pl
=> Fixes the log upload script to have the right path

serverless/.gitignore, serverless/Makefile, serverless/deplists/app.json
=> Unbreaks the serverless build

serverless/Makefile, serverless/handler.pl
=> Adds the handler to the build process

serverless/Makefile
=> Adds a chmod to the Makefile so that everything actually executes

serverless/Makefile
=> Removes libperl.a from the build

serverless/bootstrap
=> Fix perl instantiation

serverless/Makefile, serverless/bootstrap
Debugging support for /opt to see what the custom structure is
Fixes: #1708
=> Adds registration for lambda layer with new name

serverless/bootstrap, tools/createdeps.pl
Adds conditional to e2 perl lambda bootstrap
Fixes #1712
=> Fixes typo in createdeps

serverless/bootstrap
=> More bash, less ruby

serverless/Makefile
=> Adds the aws lambda call to the CodeBuild makefile invocation

lambda/everything2-sitemap-generate/handler.pl, serverless/.gitignore, serverless/Makefile, serverless/bootstrap
=> Adds 7za capabilities to the serverless build to bootstrap the .zip file

cf/everything2-production.json
=> Increased the resources afforded to the cicd zips puller

cf/everything2-production.json
=> Adds the log group for the new lambda function

serverless/Makefile
=> Fixes Makefile for CodeBuild

lambda/everything2-sitemap-generate/handler.pl, serverless/Makefile
=> Adds in libxml2 binary support for XML::LibXML

lambda/everything2-sitemap-generate/handler.pl, serverless/bootstrap
=> Adds LD_LIBRARY_PATH to the handler

ecoretool/ecoretool.pl
=> Fixing ecoretool so bootstrap works properly

serverless/deplists/app.json
=> Removes Cache::Memcached from the deplist

ecore/Everything/Configuration.pm
=> Reduces the necessary items in everything.conf.json to the bare minimum

cf/everything2-production.json
=> Fixes autohealing issues and makes autoscaling listen to the ELB

cf/everything2-production.json
=> Reduces connection draining to a much more reasonable 10s

ecore/Everything/Delegation/htmlcode.pm
=> Fixes dumb length problem for password fields

ecore/Everything/Configuration.pm, vagrant/cookbooks/e2engine/attributes/default.rb, vagrant/cookbooks/e2engine/recipes/default.rb
=> Removes gitrepo from Configuration and cookbooks

ecore/Everything/Configuration.pm, t/testdata/config_2.json, t/testdata/config_3.json, tools/genRDF.pl
=> Moves site_description to mainline CONF

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes site_description as it is now a mainline property

ecore/Everything/Configuration.pm
=> Moves site_name to the top so that it can be transitioned

ecore/Everything/Page/other_users_xml_ticker.pm, nodepack/fullpage/chatterbox_xml_ticker.xml, nodepack/fullpage/cool_nodes_xml_ticker.xml, nodepack/fullpage/new_nodes_xml_ticker.xml, nodepack/fullpage/private_message_xml_ticker.xml, nodepack/fullpage/user_information_xml.xml, nodepack/fullpage/user_search_xml_ticker.xml, nodepack/setting/bounties.xml, nodepack/setting/bounty_comments.xml, nodepack/setting/bounty_number.xml, nodepack/setting/egg_commands.xml, nodepack/setting/outlaws.xml, nodepack/setting/penny_jar.xml, nodepack/setting/room_topics.xml, nodepack/stylesheet/in10se_bootstrap.xml, nodepack/superdoc/iron_noder_progress.xml, nodepack/superdoc/login.xml, nodepack/user/everyone.xml, nodepack/user/klaproth.xml, nodepack/user/webster_1913.xml, tools/genRDF.pl
=> Remove site_name from system hash and update appropriate consumers

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes site_name from system

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Moves create_new_user to top-level configuration

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes create_new_user from the system pieces

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes default_guest_node from the system vars

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes default_guest_node from the attributes file

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/htmlpage.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes default_nodeletgroup

vagrant/cookbooks/e2engine/attributes/default.rb
=> Remove default_nodeletgroup attribute

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/container.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm
=> Makes default_node a mainline config item

nodepack/setting/room_topics.xml, nodepack/superdoc/login.xml, nodepack/user/everyone.xml, nodepack/user/virgil.xml, nodepack/user/webster_1913.xml
=> Removes the default node call from the superdoc login page

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes default_node from attributes

t/testdata/config_2.json, t/testdata/config_3.json, vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes default_theme, which was no longer used

ecore/Everything/Configuration.pm, ecore/Everything/HTML.pm, ecore/Everything/Router.pm, t/testdata/config_2.json, t/testdata/config_3.json, tools/genRDF.pl
=> Fixes the default_duplicates_node from being in system

vagrant/cookbooks/e2engine/attributes/default.rb
=> Remove default_duplicates_node from attributes

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/document.pm, ecore/Everything/HTML.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes not_found_node from system

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes the not_found_node attribute

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/HTML.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes search_results from system

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removed search_results from attributes

nodepack/superdoc/wheel_of_surprise.xml
=> Potentially fix issues with the wheel of surprise

ecore/Everything/Configuration.pm, ecore/Everything/HTML.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Pull permission denied out of system vars

vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes permission_denied attribute

ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm, ecore/Everything/Delegation/nodelet.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Fixes the user_settings item to be a mainline status item

vagrant/cookbooks/e2engine/attributes/default.rb
=> Remove user_settings from attributes

t/testdata/config_2.json, t/testdata/config_3.json, vagrant/cookbooks/e2engine/attributes/default.rb
=> Removes generalparent_container

ecore/Everything/Configuration.pm, ecore/Everything/HTML.pm, t/testdata/config_2.json, t/testdata/config_3.json
=> Removes guest_link from system

vagrant/cookbooks/e2engine/attributes/default.rb
=> Remove guest_link

ecore/Everything/Application.pm, ecore/Everything/Configuration.pm, ecore/Everything/Delegation/htmlcode.pm
=> Moves maintainance nodes over to mainline system

nodepack/ticker/maintenance_nodes_xml_ticker.xml
=> Fixes old invokation of maintenance nodes

ecore/Everything/Configuration.pm, ecore/Everything/S3.pm, ecore/Everything/S3/BucketConfig.pm
=> Refactors the S3 configuration item

ecore/Everything/Configuration.pm
=> Sets nodecache default to 600
